#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
errors=0

require_text() {
  local file="$1"
  local text="$2"
  local label="$3"

  if grep -Fq "$text" "$repo_root/$file"; then
    echo "ok: $label"
  else
    echo "missing: $label ($file)" >&2
    errors=$((errors + 1))
  fi
}

require_file() {
  local file="$1"
  local label="$2"

  if [ -f "$repo_root/$file" ]; then
    echo "ok: $label"
  else
    echo "missing: $label ($file)" >&2
    errors=$((errors + 1))
  fi
}

require_file "shared/references/cto-orchestration-operating-model.md" "CTO operating model reference"
require_file "shared/references/delegation-protocol.md" "delegation protocol reference"
require_file "shared/references/release-train-discipline.md" "release train discipline reference"
require_file "shared/references/github-communication-protocol.md" "GitHub communication protocol reference"
require_file "shared/references/commit-pr-discipline.md" "commit and PR discipline reference"
require_file "shared/references/product-autonomy-permissions.md" "product autonomy permissions reference"
require_file "shared/references/weekly-wordpress-intelligence.md" "weekly WordPress intelligence reference"
require_file "shared/references/self-improvement-loop.md" "self-improvement loop reference"
require_file "shared/references/repo-product-docs-contract.md" "repo product docs contract reference"

require_text "wp-product-orchestrator/SKILL.md" "CTO control-plane" "orchestrator CTO control-plane language"
require_text "wp-product-orchestrator/SKILL.md" "GitHub issue-first" "orchestrator GitHub issue-first routing"
require_text "wp-product-orchestrator/SKILL.md" "Plan before delegation" "orchestrator plan-before-delegation rule"
require_text "wp-product-orchestrator/SKILL.md" "source of truth hierarchy" "orchestrator source-of-truth hierarchy"
require_text "wp-product-orchestrator/SKILL.md" "Do not create a next milestone prerelease" "orchestrator release train prerelease gate"
require_text "wp-product-orchestrator/SKILL.md" "Milestones need due dates" "orchestrator milestone due-date rule"
require_text "wp-product-orchestrator/SKILL.md" '`owner:codex` means ready' "orchestrator owner:codex ready label"
require_text "wp-product-orchestrator/SKILL.md" '`owner:me` is not a stall for reversible non-release choices' "orchestrator owner:me reversible autonomy"
require_text "wp-product-orchestrator/SKILL.md" 'Do not require `Codex:` comment prefixes' "orchestrator no Codex prefix dependency"
require_text "wp-product-orchestrator/SKILL.md" "Do not post GitHub comments for routine notifications" "orchestrator quiet GitHub comment discipline"
require_text "wp-product-orchestrator/SKILL.md" "CTO control chat thread" "orchestrator CTO chat status routing"
require_text "wp-product-orchestrator/SKILL.md" "Keep direct CTO execution limited" "orchestrator direct execution boundary"
require_text "wp-product-orchestrator/SKILL.md" "delegate at least one bounded task" "orchestrator mandatory delegation trigger"
require_text "wp-product-orchestrator/SKILL.md" "Delegation decision" "orchestrator delegation decision status line"
require_text "wp-product-orchestrator/SKILL.md" "portfolio-wide sweep across all assigned products" "orchestrator portfolio sweep"
require_text "wp-product-orchestrator/SKILL.md" "Portfolio heartbeat cadence is 2 hours" "orchestrator portfolio cadence"
require_text "wp-product-orchestrator/SKILL.md" "Product heartbeat is hourly" "orchestrator product cadence"
require_text "wp-product-orchestrator/SKILL.md" "No action after verification" "orchestrator quiet product reporting"
require_text "wp-product-orchestrator/SKILL.md" "Aculect AI Companion, WP Distraction Free View, OneSMTP, PreviewShare, and CleanLinks" "current managed product examples"
require_text "wp-product-orchestrator/SKILL.md" "design gaps" "orchestrator design contract ownership"
require_text "wp-product-orchestrator/SKILL.md" "dependency/stale-PR hygiene" "orchestrator dependency stale PR ownership"
require_text "wp-product-orchestrator/SKILL.md" "Product threads drive the next release train to ready" "orchestrator release-readiness objective"
require_text "shared/references/cto-orchestration-operating-model.md" "PR review or merge for good non-production PRs" "orchestrator non-production PR autonomy"
require_text "wp-product-orchestrator/SKILL.md" "Synthesize release-ready evidence" "orchestrator release-ready evidence"
require_text "wp-product-orchestrator/SKILL.md" "Portfolio coverage drift" "orchestrator portfolio drift classification"
require_text "wp-product-orchestrator/SKILL.md" "portfolio control room plus one long-lived product-orchestrator thread per managed plugin" "thread topology"
require_text "wp-product-orchestrator/SKILL.md" "Product threads are user-visible control threads" "product thread protection"
require_text "wp-product-orchestrator/SKILL.md" "Portfolio execution drift" "portfolio execution drift classification"
require_text "wp-product-orchestrator/SKILL.md" "Product-idea issues require web research first" "product idea research gate"
require_text "shared/references/cto-orchestration-operating-model.md" 'Assignee: `@mehul0810`' "orchestrator issue assignee rule"
require_text "wp-product-orchestrator/SKILL.md" "approved intake signal" "orchestrator owner-mentioned intake signal"
require_text "wp-product-orchestrator/SKILL.md" "Do not blindly drain milestones" "orchestrator milestone scope gate"
require_text "wp-product-orchestrator/SKILL.md" "Define release scope and priority set before implementation" "orchestrator release scope priority gate"
require_text "wp-product-orchestrator/SKILL.md" "nearest appropriate next-three milestone/release train" "orchestrator next-three milestone prioritization"
require_text "wp-product-orchestrator/SKILL.md" "competitor-neutral" "orchestrator public competitor neutrality"
require_text "shared/references/delegation-protocol.md" 'Issue branch name and PR base; never direct `main`' "worker no direct main rule"
require_text "wp-product-orchestrator/SKILL.md" 'Milestone release work uses `release/<release-version>` as branch/PR base' "orchestrator release-version branch required"
require_text "wp-product-orchestrator/SKILL.md" "never GitHub milestone ID/sequence" "orchestrator no milestone ID branch"
require_text "wp-product-orchestrator/SKILL.md" 'Never create `release/3` unless' "orchestrator no release ID branch"
require_text "wp-product-orchestrator/SKILL.md" "preserve commits, retarget PRs" "orchestrator wrong branch recovery"
require_text "wp-product-orchestrator/SKILL.md" "Only production/beta release actions need explicit" "orchestrator release-only approval"
require_text "wp-product-orchestrator/SKILL.md" "sanitized hardening PRs" "orchestrator sanitized security hardening"
require_text "wp-product-orchestrator/SKILL.md" "do not archive them unless the owner explicitly asks" "protected thread archive gate"
require_text "wp-product-orchestrator/SKILL.md" "Use tool discovery before declaring delegation unavailable" "orchestrator delegation tool discovery"
require_text "wp-product-orchestrator/SKILL.md" 'git rev-parse --show-toplevel' "orchestrator worktree repo-root verification"
require_text "wp-product-orchestrator/SKILL.md" "setup-blocked" "orchestrator setup-blocked project guard"
require_text "wp-product-orchestrator/SKILL.md" "Setup-blocked starts recovery, not a stop condition" "orchestrator setup-blocked recovery ladder"
require_text "wp-product-orchestrator/SKILL.md" "manual git worktree" "orchestrator manual git worktree recovery"
require_text "shared/references/delegation-protocol.md" "Recovered by doing Y; next work is Z" "orchestrator recovery final status"
require_text "wp-product-orchestrator/SKILL.md" "Product thread topology drift" "orchestrator stale product thread topology drift"
require_text "shared/references/delegation-protocol.md" "unusable worktree" "orchestrator unusable worktree guard"
require_text "wp-product-orchestrator/SKILL.md" "Missing milestone due dates are metadata decisions, not blanket intake or implementation blockers" "orchestrator due date not blanket blocker"
require_text "wp-product-orchestrator/SKILL.md" "Dirty or behind primary checkouts block direct edits, not fresh scoped worktree delegation" "orchestrator dirty checkout worktree delegation"
require_text "shared/references/delegation-protocol.md" "Owner action required: approve/perform Y; meanwhile I completed A/B/C" "orchestrator owner-only final status"
require_text "wp-product-orchestrator/SKILL.md" "../shared/references/delegation-protocol.md" "orchestrator delegation protocol routing"
require_text "wp-product-orchestrator/SKILL.md" "../shared/references/github-communication-protocol.md" "orchestrator GitHub communication routing"
require_text "wp-product-orchestrator/SKILL.md" "../shared/references/commit-pr-discipline.md" "orchestrator commit/PR routing"
require_text "wp-product-orchestrator/SKILL.md" "../shared/references/weekly-wordpress-intelligence.md" "orchestrator weekly intelligence routing"
require_text "wp-product-orchestrator/SKILL.md" "../shared/references/self-improvement-loop.md" "orchestrator self-improvement routing"

require_text "shared/references/cto-orchestration-operating-model.md" "Source Of Truth Hierarchy" "source-of-truth hierarchy reference section"
require_text "shared/references/cto-orchestration-operating-model.md" "GitHub Issue-First Intake" "GitHub issue-first intake reference section"
require_text "shared/references/cto-orchestration-operating-model.md" "Portfolio Sweep Discipline" "portfolio sweep reference section"
require_text "shared/references/cto-orchestration-operating-model.md" "Portfolio heartbeat: every 2 hours" "CTO portfolio cadence"
require_text "shared/references/cto-orchestration-operating-model.md" "Product heartbeat: hourly" "CTO product cadence"
require_text "shared/references/cto-orchestration-operating-model.md" "Quiet products must be included with" "quiet products inclusion"
require_text "shared/references/cto-orchestration-operating-model.md" "Open PRs/issues and CI/release blockers" "portfolio minimum status fields"
require_text "shared/references/cto-orchestration-operating-model.md" "Dependabot/dependency/tooling PRs and stale PRs" "portfolio dependency and stale PR sweep"
require_text "shared/references/cto-orchestration-operating-model.md" "Thread Topology" "thread topology reference section"
require_text "shared/references/cto-orchestration-operating-model.md" "Product Thread Ownership" "product thread ownership reference section"
require_text "shared/references/cto-orchestration-operating-model.md" "drive the next release train to release-ready" "CTO release-readiness objective"
require_text "shared/references/cto-orchestration-operating-model.md" "Use any relevant skill or capability" "CTO skill routing for readiness"
require_text "shared/references/cto-orchestration-operating-model.md" "Portfolio Thread Ownership" "portfolio thread ownership reference section"
require_text "shared/references/cto-orchestration-operating-model.md" "WordPress.org Product Loop" "wordpress.org product loop"
require_text "shared/references/cto-orchestration-operating-model.md" 'Plan `Tested up to` WordPress 7.0' "CTO WordPress tested up metadata"
require_text "shared/references/cto-orchestration-operating-model.md" "Competitor names may inform private research" "competitor-neutral public issues"
require_text "shared/references/cto-orchestration-operating-model.md" 'Assignee: `@mehul0810`' "issue assignee rule"
require_text "shared/references/cto-orchestration-operating-model.md" "approved backlog/intake signal" "CTO owner-mentioned approved intake"
require_text "shared/references/cto-orchestration-operating-model.md" "among the next three" "CTO next-three milestone prioritization"
require_text "shared/references/cto-orchestration-operating-model.md" "Do not blindly drain every issue in a milestone" "CTO milestone scope gate"
require_text "shared/references/cto-orchestration-operating-model.md" "milestone/release scope and priority set are defined" "CTO release scope priority gate"
require_text "shared/references/cto-orchestration-operating-model.md" 'Reserve `Owner decisions needed` for production/beta release actions or non-reversible conflicts' "CTO owner decision hard-gate scope"
require_text "shared/references/cto-orchestration-operating-model.md" 'Use `owner:codex` for items ready' "CTO owner:codex ready label"
require_text "shared/references/cto-orchestration-operating-model.md" '`owner:me` is not a stall for reversible non-release choices' "CTO owner:me reversible autonomy"
require_text "shared/references/cto-orchestration-operating-model.md" "current milestone has no ready work" "CTO next milestone fallback"
require_text "shared/references/cto-orchestration-operating-model.md" "create proactive review work" "CTO proactive review work"
require_text "shared/references/cto-orchestration-operating-model.md" "WordPress.org visibility, accessibility, or sanitized hardening" "CTO proactive ecosystem review"
require_text "shared/references/cto-orchestration-operating-model.md" "PR review or merge for good non-production PRs" "CTO non-production PR autonomy"
require_text "shared/references/cto-orchestration-operating-model.md" "merged PRs, remaining open issues, CI/package validation" "CTO release-ready evidence"
require_text "shared/references/cto-orchestration-operating-model.md" "Security-sensitive findings must not become public issues" "CTO sanitized security issue rule"
require_text "shared/references/cto-orchestration-operating-model.md" 'Do not require owner comments to start with `Codex:`' "CTO no Codex prefix dependency"
require_text "shared/references/cto-orchestration-operating-model.md" "request exact saved Codex projects" "portfolio exact project setup guidance"
require_text "shared/references/cto-orchestration-operating-model.md" "Ask the owner before interrupting" "portfolio protected product thread action gate"
require_text "shared/references/cto-orchestration-operating-model.md" "recover first" "portfolio setup-blocked recovery guidance"
require_text "shared/references/delegation-protocol.md" "Delegated Thread Prompt" "delegated thread/worktree protocol"
require_text "shared/references/delegation-protocol.md" "no subdelegation unless the parent CTO thread asks" "delegated no-subdelegation rule"
require_text "shared/references/delegation-protocol.md" "Direct Execution Boundary" "direct CTO execution boundary"
require_text "shared/references/delegation-protocol.md" "delegate at least one bounded task" "mandatory delegation trigger"
require_text "shared/references/delegation-protocol.md" "Delegation decision: Delegated|Direct|Deferred" "delegation decision check-in line"
require_text "shared/references/delegation-protocol.md" "Prefer multi-agent/subagent delegation" "prefer internal subagent delegation"
require_text "shared/references/delegation-protocol.md" "Never archive user-created control or skill threads" "do not archive owner control threads"
require_text "shared/references/delegation-protocol.md" "Missing delegation after strategy" "delegation self-improvement classification"
require_text "shared/references/delegation-protocol.md" "Thread Boundary" "delegation thread boundary"
require_text "shared/references/delegation-protocol.md" 'Issue branch name and PR base; never direct `main`' "worker branch/base guard"
require_text "shared/references/delegation-protocol.md" "archive protected product/control threads" "worker protected archive guard"
require_text "shared/references/delegation-protocol.md" 'Look for `list_projects`, `create_thread`, `fork_thread`, `send_message_to_thread`' "delegation tool discovery requirement"
require_text "shared/references/delegation-protocol.md" "Worktree Creation Guard" "delegation worktree creation guard section"
require_text "shared/references/delegation-protocol.md" 'git rev-parse --show-toplevel' "delegation repo-root verification command"
require_text "shared/references/delegation-protocol.md" "Exact-project preflight" "delegation exact project preflight"
require_text "shared/references/delegation-protocol.md" "setup-blocked: missing exact repo project" "delegation missing repo project blocker"
require_text "shared/references/delegation-protocol.md" "unusable worktree" "delegation unusable worktree classification"
require_text "shared/references/delegation-protocol.md" "Unblock-First Recovery Ladder" "delegation unblock-first recovery ladder"
require_text "shared/references/delegation-protocol.md" "Research, GitHub issue intake, support/forum triage" "delegation direct non-code work path"
require_text "shared/references/delegation-protocol.md" "Read-only code mapping or evidence" "delegation read-only mapping path"
require_text "shared/references/delegation-protocol.md" 'manual `git worktree`' "delegation manual git worktree recovery"
require_text "shared/references/delegation-protocol.md" "Notify the owner only when the remaining action is owner-only" "delegation owner-only notification gate"
require_text "shared/references/delegation-protocol.md" "Recovered by doing Y; next work is Z" "delegation recovered final status"
require_text "shared/references/delegation-protocol.md" "Stale active turn handling" "delegation stale active turn handling"
require_text "shared/references/delegation-protocol.md" "Dirty or behind primary checkouts block direct edits" "delegation dirty primary checkout rule"
require_text "shared/references/delegation-protocol.md" "OneSMTP #73" "delegation explicit branch-model blocker"
require_text "shared/references/release-train-discipline.md" "Do not create a next milestone prerelease" "release train production gate"
require_text "shared/references/release-train-discipline.md" "Milestones need due dates" "milestone due-date reference rule"
require_text "shared/references/release-train-discipline.md" '`main` is production release space only' "main production-only rule"
require_text "shared/references/release-train-discipline.md" "owner testing confirmation" "owner testing release readiness"
require_text "shared/references/release-train-discipline.md" 'Tested up to` WordPress 7.0' "release WordPress tested up metadata"
require_text "shared/references/release-train-discipline.md" "missing due date alone" "release missing due date not blocker"
require_text "shared/references/release-train-discipline.md" 'Milestone release work must target `release/<release-version>`' "release version branch required"
require_text "shared/references/release-train-discipline.md" "not the GitHub milestone ID or sequence number" "release no milestone ID branch"
require_text "shared/references/release-train-discipline.md" "wrong milestone-ID branch" "release wrong branch recovery"
require_text "shared/references/release-train-discipline.md" "Normal product orchestration, issue intake, implementation, hardening PRs" "release normal work no approval"
require_text "shared/references/release-train-discipline.md" "good non-production PR review/merge" "release non-production PR autonomy"
require_text "shared/references/release-train-discipline.md" "When the train is release-ready" "release-ready notification rule"
require_text "shared/references/github-communication-protocol.md" "GitHub Issue And PR Comments" "GitHub issue and PR comments protocol"
require_text "shared/references/github-communication-protocol.md" "Label-Driven Ready State" "GitHub label-driven ready state"
require_text "shared/references/github-communication-protocol.md" '`owner:codex`: ready for Codex/orchestrator/worker action' "GitHub owner:codex ready label"
require_text "shared/references/github-communication-protocol.md" '`owner:me`: waiting on `@mehul0810` for true hard gates' "GitHub owner:me hard gate label"
require_text "shared/references/github-communication-protocol.md" "reversible and non-release" "GitHub owner:me reversible autonomy"
require_text "shared/references/github-communication-protocol.md" 'Do not require owner comments to start with `Codex:`' "GitHub no Codex prefix dependency"
require_text "shared/references/github-communication-protocol.md" 'relabels `owner:codex`' "GitHub resume after relabel"
require_text "shared/references/github-communication-protocol.md" "Write GitHub comments sparingly" "quiet GitHub write discipline"
require_text "shared/references/github-communication-protocol.md" "Do not post GitHub comments for routine notifications" "no routine GitHub notification comments"
require_text "shared/references/github-communication-protocol.md" "CTO control chat thread" "routine status routes to CTO chat"
require_text "shared/references/commit-pr-discipline.md" "type(scope): concise action" "commit convention"
require_text "shared/references/commit-pr-discipline.md" "Every PR must include" "PR template requirements"
require_text "shared/references/commit-pr-discipline.md" '`main` is production release space only' "commit-pr main production-only rule"
require_text "shared/references/commit-pr-discipline.md" "Worker PR Rule" "worker one issue one PR rule"
require_text "shared/references/commit-pr-discipline.md" "verified development base" "commit-pr verified development base"
require_text "shared/references/commit-pr-discipline.md" 'Milestone-based work must create or use `release/<release-version>`' "commit-pr release-version branch required"
require_text "shared/references/commit-pr-discipline.md" "not the GitHub milestone ID or sequence number" "commit-pr no milestone ID branch"
require_text "shared/references/commit-pr-discipline.md" "retarget open PRs" "commit-pr wrong branch recovery"
require_text "shared/references/commit-pr-discipline.md" '`develop` is for unmilestoned development integration' "commit-pr develop unmilestoned rule"
require_text "shared/references/product-autonomy-permissions.md" "Only production or beta release actions require explicit current" "autonomy release-only approval"
require_text "shared/references/product-autonomy-permissions.md" 'do not stall on `owner:me`' "autonomy owner:me no stall"
require_text "shared/references/product-autonomy-permissions.md" "PR review/merge for good non-production PRs" "autonomy non-production PR merge"
require_text "shared/references/product-autonomy-permissions.md" "Security-sensitive findings should not become public issues" "autonomy sanitized security rule"
require_text "shared/references/product-queue-triage.md" "Product-idea issues require web research" "product idea web research rule"
require_text "shared/references/product-queue-triage.md" "product-thread objective is release readiness" "queue release-readiness objective"
require_text "shared/references/product-queue-triage.md" 'Assign to `@mehul0810`' "product issue assignee rule"
require_text "shared/references/product-queue-triage.md" "Competitor names may inform private research" "product issue competitor-neutral rule"
require_text "shared/references/product-queue-triage.md" "Owner-mentioned work is approved intake signal, not an owner-decision blocker" "queue owner-mentioned approved intake"
require_text "shared/references/product-queue-triage.md" "Do not blindly drain every issue in a milestone" "queue milestone scope gate"
require_text "shared/references/product-queue-triage.md" "define the milestone/release scope and priority set" "queue release scope priority gate"
require_text "shared/references/product-queue-triage.md" 'Ensure `owner:codex` and `owner:me` labels exist' "queue ensure owner labels"
require_text "shared/references/product-queue-triage.md" '`owner:me` is not a stall for reversible non-release choices' "queue owner:me reversible autonomy"
require_text "shared/references/product-queue-triage.md" "current milestone has no ready work" "queue next milestone fallback"
require_text "shared/references/product-queue-triage.md" "create proactive review work" "queue proactive review work"
require_text "shared/references/product-queue-triage.md" "WordPress.org visibility, accessibility, or sanitized hardening" "queue proactive ecosystem review"
require_text "shared/references/product-queue-triage.md" 'Tested up to` WordPress 7.0' "queue WordPress tested up metadata"
require_text "shared/references/product-queue-triage.md" "Security-sensitive findings must not become public issues" "queue sanitized security issue rule"
require_text "shared/references/product-queue-triage.md" 'resume when answered and relabeled `owner:codex`' "queue resume after owner relabel"
require_text "shared/references/product-queue-triage.md" "nearest appropriate milestone or release train among the next three" "queue next-three milestone prioritization"
require_text "shared/references/product-queue-triage.md" "Missing milestone due dates or branch-policy gaps are not blanket blockers for owner-approved intake" "queue owner-approved intake metadata blocker"
require_text "shared/references/product-queue-triage.md" "production/beta release action" "queue owner decision hard-gate scope"
require_text "shared/references/product-queue-triage.md" "Design Contract Intake" "queue design contract intake"
require_text "shared/references/product-queue-triage.md" 'Create focused GitHub issues to add or adapt `DESIGN.md`' "queue design issue rule"
require_text "shared/references/product-queue-triage.md" 'Do not merge Dependabot or dependency PRs directly into `main`' "queue no dependabot main merge"
require_text "shared/references/product-queue-triage.md" "Consolidate relevant dependency/tooling updates into one duplicate-screened GitHub issue" "queue dependency consolidation"
require_text "shared/references/product-queue-triage.md" "close with a durable GitHub comment" "queue stale PR durable closure comment"
require_text "shared/references/product-queue-triage.md" "checking comments, reviews, labels, and milestones first" "queue stale PR evidence guard"
require_text "shared/references/product-queue-triage.md" "not blanket blockers for owner-approved intake" "queue due date blocker discipline"
require_text "shared/references/product-queue-triage.md" 'Milestone work must use `release/<release-version>` as branch and PR base' "queue release-version branch required"
require_text "shared/references/product-queue-triage.md" "not the GitHub milestone ID or sequence number" "queue no milestone ID branch"
require_text "shared/references/product-queue-triage.md" "wrong milestone-ID branch" "queue wrong branch recovery"
require_text "shared/references/product-queue-triage.md" "fresh scoped worktree delegation" "queue dirty checkout worktree delegation"
require_text "shared/references/product-queue-triage.md" "Release-Ready Notification" "queue release-ready notification section"
require_text "shared/references/product-queue-triage.md" "Merged PRs and included scope" "queue release-ready merged PR evidence"
require_text "shared/references/weekly-wordpress-intelligence.md" "Weekly WordPress Ecosystem Intelligence" "weekly WordPress ecosystem intelligence"
require_text "shared/references/self-improvement-loop.md" "Self-Improvement Loop" "self-improvement loop"
require_text "shared/references/self-improvement-loop.md" "Stale Learning Lifecycle" "self-improvement stale learning lifecycle"
require_text "shared/references/self-improvement-loop.md" "Durable Artifact Dedupe" "self-improvement durable artifact dedupe"
require_text "shared/references/self-improvement-loop.md" "Supersede note created" "self-improvement stale outcome labels"
require_text "shared/references/self-improvement-loop.md" "Open PRs and issues" "self-improvement duplicate artifact checks"
require_text "shared/references/self-improvement-loop.md" "Missing delegation after strategy" "self-improvement missing delegation label"
require_text "shared/references/self-improvement-loop.md" "Portfolio coverage drift" "self-improvement portfolio drift label"
require_text "shared/references/self-improvement-loop.md" "Portfolio execution drift" "self-improvement portfolio execution label"
require_text "shared/references/self-improvement-loop.md" "Product thread topology drift" "self-improvement topology drift label"
require_text "shared/references/self-improvement-loop.md" "Delegation unavailable without tool discovery" "self-improvement tool discovery label"
require_text "shared/references/self-improvement-loop.md" "Setup-blocked polling loop" "self-improvement setup-blocked polling label"
require_text "shared/references/self-improvement-loop.md" "Stale active product thread" "self-improvement stale active thread label"
require_text "shared/references/self-improvement-loop.md" "Blanket blocker from due date, release branch, or dirty primary checkout" "self-improvement blanket blocker label"
require_text "shared/references/self-improvement-loop.md" "Stale Learning Lifecycle" "self-improvement stale-learning lifecycle section"
require_text "shared/references/self-improvement-loop.md" "Add" "self-improvement add lifecycle outcome"
require_text "shared/references/self-improvement-loop.md" "Correct" "self-improvement correct lifecycle outcome"
require_text "shared/references/self-improvement-loop.md" "Retire" "self-improvement retire lifecycle outcome"
require_text "shared/references/self-improvement-loop.md" "Supersede" "self-improvement supersede lifecycle outcome"
require_text "shared/references/self-improvement-loop.md" "Keep Watching" "self-improvement keep-watching lifecycle outcome"
require_text "shared/references/self-improvement-loop.md" "Ignore" "self-improvement ignore lifecycle outcome"
require_text "shared/references/self-improvement-loop.md" "Fixed now" "self-improvement fixed-now audit outcome"
require_text "shared/references/self-improvement-loop.md" "PR opened" "self-improvement PR-opened audit outcome"
require_text "shared/references/self-improvement-loop.md" "Supersede note created" "self-improvement supersede-note-created audit outcome"
require_text "shared/references/self-improvement-loop.md" "Detected only" "self-improvement detected-only audit outcome"
require_text "shared/references/self-improvement-loop.md" "Duplicate durable artifact" "self-improvement duplicate artifact label"
require_text "shared/references/self-improvement-loop.md" "Stale local-ref conclusion" "self-improvement stale local-ref label"
require_text "shared/references/self-improvement-loop.md" "Unclassified stale learning" "self-improvement unclassified stale learning label"
require_text "shared/references/self-improvement-loop.md" "Durable Artifact Dedupe" "self-improvement durable artifact dedupe section"
require_text "shared/references/self-improvement-loop.md" "Normalized rule slug" "self-improvement normalized slug dedupe"
require_text "shared/references/self-improvement-loop.md" "Open PRs and issues" "self-improvement open PR/issue dedupe"
require_text "shared/references/self-improvement-loop.md" "Recently merged PRs and closed issues" "self-improvement merged PR/closed issue dedupe"
require_text "shared/references/self-improvement-loop.md" "one compact rollup per date" "self-improvement same-day rollup dedupe"
require_text "shared/references/repo-product-docs-contract.md" "Product Truth Does Not Live Only In The Skill" "repo product docs contract"
require_text "shared/references/repo-product-docs-contract.md" '`DESIGN.md`: concise product design contract' "repo DESIGN.md product design contract"
require_text "shared/references/repo-product-docs-contract.md" "not a heavy design-system spec" "repo DESIGN.md not heavy spec"
require_text "shared/references/repo-product-docs-contract.md" "duplicate-screened product issues" "repo DESIGN.md duplicate-screened issue rule"
require_text "shared/references/repo-product-docs-contract.md" "CleanLinks and Aculect first" "repo DESIGN.md product priority"

if [ "$errors" -gt 0 ]; then
  echo "orchestration behavior audit failed: $errors missing guardrail(s)" >&2
  exit 1
fi

echo "orchestration behavior audit passed"
