#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
errors=0

require_text() {
  local file="$1"
  local text="$2"
  local label="$3"

  if grep -Fq "$text" "$repo_root/$file"; then
    echo "ok: $label"
  else
    echo "missing: $label ($file)" >&2
    errors=$((errors + 1))
  fi
}

require_absent() {
  local file="$1"
  local text="$2"
  local label="$3"

  if grep -Fq "$text" "$repo_root/$file"; then
    echo "unexpected: $label ($file)" >&2
    errors=$((errors + 1))
  else
    echo "ok: $label"
  fi
}

require_file() {
  local file="$1"
  local label="$2"

  if [ -f "$repo_root/$file" ]; then
    echo "ok: $label"
  else
    echo "missing: $label ($file)" >&2
    errors=$((errors + 1))
  fi
}

require_file "wp-portfolio-cto/SKILL.md" "portfolio CTO skill"
require_file "wp-portfolio-cto/references/router.md" "portfolio CTO router"
require_file "wp-product-orchestrator/SKILL.md" "product orchestrator skill"
require_file "wp-product-orchestrator/references/router.md" "product orchestrator router"
require_file "templates/portfolio/PORTFOLIO.md" "runtime portfolio manifest template"
require_file "shared/references/cto-orchestration-operating-model.md" "CTO operating model reference"
require_file "shared/references/delegation-protocol.md" "delegation protocol reference"
require_file "shared/references/release-train-discipline.md" "release train discipline reference"
require_file "shared/references/github-communication-protocol.md" "GitHub communication protocol reference"
require_file "shared/references/commit-pr-discipline.md" "commit and PR discipline reference"
require_file "shared/references/product-autonomy-permissions.md" "product autonomy permissions reference"
require_file "shared/references/weekly-wordpress-intelligence.md" "weekly WordPress intelligence reference"
require_file "shared/references/self-improvement-loop.md" "self-improvement loop reference"
require_file "shared/references/disposable-proof-environment-lifecycle.md" "disposable proof-environment lifecycle reference"
require_file "shared/references/repo-product-docs-contract.md" "repo product docs contract reference"
require_file "shared/references/context-window-discipline.md" "context window discipline reference"
require_file "shared/references/project-subagent-routing.md" "project subagent routing reference"
require_file "shared/references/rolling-milestone-triage.md" "rolling milestone triage reference"
require_file "shared/references/heartbeat-checkin-discipline.md" "heartbeat check-in discipline reference"
require_file "shared/references/authority-growth-lane.md" "authority and growth lane reference"
require_file "shared/references/enterprise-design-judgment.md" "enterprise design judgment reference"

# Hot paths hold role kernels and route detail to one focused reference.
require_text "wp-portfolio-cto/SKILL.md" "cross-product control room" "portfolio CTO control room language"
require_text "wp-portfolio-cto/SKILL.md" "Never hardcode transient portfolio state" "portfolio runtime-state rule"
require_text "wp-portfolio-cto/SKILL.md" "Route backlog" "portfolio routes product execution"
require_text "wp-portfolio-cto/SKILL.md" "Portfolio execution drift" "portfolio execution drift classification"
require_text "wp-portfolio-cto/SKILL.md" "one non-material heartbeat on a release blocker" "portfolio release-blocker escalation"
require_text "wp-portfolio-cto/SKILL.md" "Never archive owner-created portfolio, product, or skill threads" "portfolio protected thread gate"
require_text "wp-portfolio-cto/SKILL.md" "compact quality matrix" "portfolio release quality summary"
require_text "wp-portfolio-cto/SKILL.md" "Skill PO lane" "portfolio skill routing"
require_text "wp-portfolio-cto/SKILL.md" "standing validated direct-main publication policy" "portfolio agent publication rule"
require_text "wp-portfolio-cto/SKILL.md" "references/router.md" "portfolio focused router"
require_text "wp-portfolio-cto/SKILL.md" "Context decision: Compact|Fresh thread|Continue" "portfolio context decision"
require_text "wp-portfolio-cto/SKILL.md" "Retry oversized/failed connector calls once with a smaller payload" "portfolio bounded payload retry"
require_text "wp-portfolio-cto/SKILL.md" "Studio lifecycle is report-only" "portfolio proof-environment fail-closed protection"

require_text "wp-product-orchestrator/SKILL.md" "one long-lived product control thread" "orchestrator one-product language"
require_text "wp-product-orchestrator/SKILL.md" "Cross-product governance belongs" "orchestrator portfolio handoff"
require_text "wp-product-orchestrator/SKILL.md" "issue-first, duplicate-screened, PR-sized intake" "orchestrator issue-first intake"
require_text "wp-product-orchestrator/SKILL.md" "Define release scope and priority before implementation" "orchestrator release-scope gate"
require_text "wp-product-orchestrator/SKILL.md" "Plan scope, acceptance criteria, non-goals" "orchestrator plan-before-delegation kernel"
require_text "wp-product-orchestrator/SKILL.md" "Route by artifact" "orchestrator specialist routing"
require_text "wp-product-orchestrator/SKILL.md" "Dirty primary checkouts block direct edits, not a clean worktree" "orchestrator clean-worktree recovery"
require_text "wp-product-orchestrator/SKILL.md" 'release/<release-version>' "orchestrator release-version branch"
require_text "wp-product-orchestrator/SKILL.md" "Do not start the next train's prerelease" "orchestrator release-train gate"
require_text "wp-product-orchestrator/SKILL.md" "destructive or transfer actions, uncertain side effects" "orchestrator owner approval boundary"
require_text "wp-product-orchestrator/SKILL.md" "issue-side before evidence and PR-side after screenshots" "orchestrator design proof"
require_text "wp-product-orchestrator/SKILL.md" "Default to disposable non-Studio proof" "orchestrator proof-environment default"
require_text "wp-product-orchestrator/SKILL.md" "Studio lifecycle is report-only without" "orchestrator proof-environment policy gate"
require_text "wp-product-orchestrator/SKILL.md" "delta-first, owner-readable check-ins" "orchestrator check-in discipline"
require_text "wp-product-orchestrator/SKILL.md" "topology/process failure" "orchestrator failure classification"
require_text "wp-product-orchestrator/SKILL.md" "references/router.md" "orchestrator focused router"
require_text "wp-product-orchestrator/SKILL.md" "Delegation decision: Delegated|Direct|Deferred" "orchestrator delegation decision"
require_text "wp-product-orchestrator/SKILL.md" "Context decision: Compact|Fresh thread|Continue" "orchestrator context decision"

# Routers expose canonical detail without making every turn load it.
require_text "wp-portfolio-cto/references/router.md" "cto-orchestration-operating-model.md" "portfolio topology route"
require_text "wp-portfolio-cto/references/router.md" "heartbeat-checkin-discipline.md" "portfolio heartbeat route"
require_text "wp-portfolio-cto/references/router.md" "weekly-wordpress-intelligence.md" "portfolio intelligence route"
require_text "wp-portfolio-cto/references/router.md" "repo-product-docs-contract.md" "portfolio repo-doc route"
require_text "wp-portfolio-cto/references/router.md" "authority-growth-lane.md" "portfolio authority-growth route"
require_text "wp-portfolio-cto/references/router.md" "disposable-proof-environment-lifecycle.md" "portfolio proof-environment route"
require_text "wp-portfolio-cto/references/router.md" "Resolve products, priorities, repo paths, thread IDs, and cadence" "portfolio runtime manifest routing"
require_text "wp-product-orchestrator/references/router.md" "product-queue-triage.md" "product queue route"
require_text "wp-product-orchestrator/references/router.md" "product-autonomy-permissions.md" "product authority route"
require_text "wp-product-orchestrator/references/router.md" "release-train-discipline.md" "product release route"
require_text "wp-product-orchestrator/references/router.md" "delegation-protocol.md" "product delegation route"
require_text "wp-product-orchestrator/references/router.md" "github-communication-protocol.md" "product GitHub route"
require_text "wp-product-orchestrator/references/router.md" "repo-product-docs-contract.md" "product repo-doc route"
require_text "wp-product-orchestrator/references/router.md" "authority-growth-lane.md" "product authority-growth route"
require_text "wp-product-orchestrator/references/router.md" "weekly-wordpress-intelligence.md" "product intelligence route"
require_text "wp-product-orchestrator/references/router.md" "self-improvement-loop.md" "product self-improvement route"
require_text "wp-product-orchestrator/references/router.md" "disposable-proof-environment-lifecycle.md" "product proof-environment route"

# The canonical operating model owns topology and authority, not transient portfolio data.
require_text "shared/references/cto-orchestration-operating-model.md" "Runtime Portfolio Contract" "CTO runtime portfolio contract"
require_text "shared/references/cto-orchestration-operating-model.md" "Do not hardcode transient product lists" "CTO transient-state exclusion"
require_text "shared/references/cto-orchestration-operating-model.md" "Thread Topology" "CTO thread topology"
require_text "shared/references/cto-orchestration-operating-model.md" "Loop-Stack Operating Model" "CTO loop-stack model"
require_text "shared/references/cto-orchestration-operating-model.md" "Never archive user-created portfolio, product, or skill threads" "CTO protected thread gate"
require_text "shared/references/cto-orchestration-operating-model.md" "Portfolio Thread Ownership" "CTO portfolio ownership"
require_text "shared/references/cto-orchestration-operating-model.md" "Product Thread Ownership" "CTO product ownership"
require_text "shared/references/cto-orchestration-operating-model.md" "Source Of Truth Hierarchy" "CTO source hierarchy"
require_text "shared/references/cto-orchestration-operating-model.md" "Bounded Live Check Policy" "CTO bounded live-check policy"
require_text "shared/references/cto-orchestration-operating-model.md" "retry at most once for the narrow missing signal" "CTO bounded retry"
require_text "shared/references/cto-orchestration-operating-model.md" "fails closed with a concise owner-visible blocker" "CTO release fail-closed rule"
require_text "shared/references/cto-orchestration-operating-model.md" "Authority Boundary" "CTO authority boundary"
require_text "shared/references/cto-orchestration-operating-model.md" "Require explicit current approval" "CTO hard gates"
require_text "shared/references/cto-orchestration-operating-model.md" "Sensitive security details stay private" "CTO security disclosure boundary"
require_text "shared/references/cto-orchestration-operating-model.md" "strongest suitable available model" "CTO dynamic capability escalation"
require_text "shared/references/cto-orchestration-operating-model.md" "Skill PO lane" "CTO skill lane"
require_text "shared/references/commit-pr-discipline.md" 'validated changes commit and push directly to `main` by default' "agent control-plane direct-main default"
require_text "AGENTS.md" "Do not create feature branches or PRs" "agent-skills no-branch default"
require_text "skill-evals/wp-portfolio-cto-scenarios.md" "does not create a branch or PR" "agent control-plane publication eval"
require_text "shared/references/cto-orchestration-operating-model.md" "Focused Routing" "CTO focused routing"

# Regression guards: live portfolio state belongs in manifests/automation, not normative skills.
require_absent "wp-portfolio-cto/SKILL.md" "Aculect AI Companion" "portfolio hot path has no product list"
require_absent "wp-product-orchestrator/SKILL.md" "OneCaptcha and ThemeRouter" "product hot path has no priority list"
require_absent "shared/references/cto-orchestration-operating-model.md" "every 30 minutes" "CTO model has no fixed cadence"
require_absent "shared/references/cto-orchestration-operating-model.md" "every 15 minutes" "CTO model has no fixed product cadence"
require_absent "skill-evals/wp-portfolio-cto-scenarios.md" "every 30 minutes" "CTO eval has no fixed cadence"
require_absent "skill-evals/wp-product-orchestrator-scenarios.md" "every 15 minutes" "PO eval has no fixed cadence"
require_absent "shared/references/delegation-protocol.md" "OneSMTP #73" "delegation reference has no transient issue"
require_absent "shared/references/release-train-discipline.md" 'Tested up to` WordPress 7.0' "release reference has no fixed WordPress target"
require_absent "shared/references/product-queue-triage.md" 'Tested up to` WordPress 7.0' "queue reference has no fixed WordPress target"
require_absent "shared/references/repo-product-docs-contract.md" "CleanLinks and Aculect first" "repo-doc reference has no transient product priority"
require_text "shared/references/delegation-protocol.md" "Delegated Thread Prompt" "delegated thread/worktree protocol"
require_text "shared/references/delegation-protocol.md" "Push planning into the issue body and delegated prompt" "delegation front-loaded planning"
require_text "shared/references/delegation-protocol.md" '`CTO Worker <Task Name>`' "delegation worker-thread naming"
require_text "shared/references/delegation-protocol.md" "Worker lifecycle owner is the creator" "delegation worker lifecycle creator ownership"
require_text "shared/references/delegation-protocol.md" "If a PO creates a worker thread" "delegation PO worker cleanup ownership"
require_text "shared/references/delegation-protocol.md" "execution rooms, not control rooms" "delegation execution-room boundary"
require_text "shared/references/delegation-protocol.md" 'Use a `Worker Threads` execution room' "delegation worker-thread routing"
require_text "shared/references/delegation-protocol.md" "Screenshot requirement when admin, editor, frontend, style, layout, UX" "delegated screenshot prompt requirement"
require_text "shared/references/delegation-protocol.md" "Suggested model/reasoning when useful" "delegated model reasoning hint"
require_text "shared/references/delegation-protocol.md" "or subdelegation" "delegated no-subdelegation rule"
require_text "shared/references/delegation-protocol.md" "Or explicit no-edit boundary when read-only" "delegated no-edit boundary rule"
require_text "shared/references/delegation-protocol.md" "Stop condition and summary requirements" "delegated stop-condition rule"
require_text "shared/references/delegation-protocol.md" "Direct Execution Boundary" "direct CTO execution boundary"
require_text "shared/references/delegation-protocol.md" "delegate at least one bounded task" "mandatory delegation trigger"
require_text "shared/references/delegation-protocol.md" "Delegation decision: Delegated|Direct|Deferred" "delegation decision check-in line"
require_text "shared/references/delegation-protocol.md" 'empty completed turn, `systemError`, missing proof, wrong path/base/model lane, repeated owner-instruction drift' "delegation topology drift failure modes"
require_text "shared/references/delegation-protocol.md" "archive/delete the disposable worker" "delegation disposable worker cleanup"
require_text "shared/references/delegation-protocol.md" "files/issues/PRs touched, validation/proof, blockers, risks, and handoff needs" "delegation final summary contents"
require_text "shared/references/heartbeat-checkin-discipline.md" "Material changes" "heartbeat material changes section"
require_text "shared/references/heartbeat-checkin-discipline.md" "Blocked" "heartbeat blocked section"
require_text "shared/references/heartbeat-checkin-discipline.md" "Owner decisions" "heartbeat owner decisions section"
require_text "shared/references/heartbeat-checkin-discipline.md" "Codex-owned next actions" "heartbeat codex-owned next actions section"
require_text "shared/references/heartbeat-checkin-discipline.md" "PO active work/delegations" "heartbeat active work section"
require_text "shared/references/heartbeat-checkin-discipline.md" "Quiet products with evidence" "heartbeat quiet evidence section"
require_text "shared/references/heartbeat-checkin-discipline.md" "Cadence/automation changes" "heartbeat cadence section"
require_text "shared/references/heartbeat-checkin-discipline.md" "Partial Result Rule" "heartbeat partial result section"
require_text "shared/references/heartbeat-checkin-discipline.md" "Do not leave the heartbeat in progress for hours" "heartbeat no long in-progress timeout loop"
require_text "shared/references/heartbeat-checkin-discipline.md" "State whether owner decisions changed or stayed unchanged" "heartbeat partial owner decision state"
require_text "shared/references/heartbeat-checkin-discipline.md" "next retry point or cadence adjustment" "heartbeat partial retry cadence"
require_text "shared/references/heartbeat-checkin-discipline.md" "Thread Health And Drift" "heartbeat drift section"
require_text "shared/references/heartbeat-checkin-discipline.md" "one non-material PO heartbeat is enough to escalate" "heartbeat release blocker immediate escalation"
require_text "shared/references/heartbeat-checkin-discipline.md" "wrong model/reasoning lane causing retries or weak evidence" "heartbeat wrong model lane drift"
require_text "shared/references/heartbeat-checkin-discipline.md" 'The `DONT_NOTIFY` message must be one sentence' "heartbeat quiet one-sentence rule"
require_text "shared/references/heartbeat-checkin-discipline.md" "exception reporting plus a compact coverage line" "heartbeat portfolio exception reporting rule"
require_text "shared/references/heartbeat-checkin-discipline.md" "Current objective" "heartbeat product objective field"
require_text "shared/references/heartbeat-checkin-discipline.md" "Evidence" "heartbeat product evidence field"
require_text "shared/references/heartbeat-checkin-discipline.md" 'Avoid phrases like `no update`, `nothing new`, or `still monitoring`' "heartbeat anti-vague-quiet rule"
require_text "shared/references/heartbeat-checkin-discipline.md" "owner-readable, not as a raw tool log" "heartbeat owner-readable rule"
require_text "shared/references/heartbeat-checkin-discipline.md" "Avoid long SHAs, raw API/XML shapes" "heartbeat no-log-dump rule"
require_text "shared/references/heartbeat-checkin-discipline.md" "Do not paste long heartbeat XML, PR bodies, diffs, screenshot lists, or raw tool output into follow-up prompts" "heartbeat prompt-payload rule"
require_text "shared/references/heartbeat-checkin-discipline.md" "What changed" "heartbeat plain-english changed section"
require_text "shared/references/heartbeat-checkin-discipline.md" "What is blocked" "heartbeat plain-english blocked section"
require_text "shared/references/heartbeat-checkin-discipline.md" "What owner needs to decide" "heartbeat plain-english owner section"
require_text "shared/references/heartbeat-checkin-discipline.md" "What Codex will do next" "heartbeat plain-english codex-next section"
require_text "shared/references/heartbeat-checkin-discipline.md" 'Replace vague terms like `owner-gated`' "heartbeat explicit-decision wording"
require_text "shared/references/heartbeat-checkin-discipline.md" "does it block current work; what would unblock it" "heartbeat dirty-blocker translation"
require_text "shared/references/heartbeat-checkin-discipline.md" 'If a connector returns `Bad Request`, retry once with a strictly smaller payload' "heartbeat bad-request retry rule"
require_text "shared/references/heartbeat-checkin-discipline.md" "Translate PO outputs into owner-facing portfolio language" "heartbeat portfolio translation rule"
require_text "shared/references/heartbeat-checkin-discipline.md" "Repeated quiet status should trigger cadence reduction/pause or a proactive discovery lane" "heartbeat repeated quiet cadence rule"
require_text "shared/references/heartbeat-checkin-discipline.md" "CTO must not merely relay PO output" "heartbeat CTO intervention rule"
require_text "shared/references/heartbeat-checkin-discipline.md" "The same quiet state appears twice while active work or a release train still exists" "heartbeat repeated quiet CTO trigger"
require_text "shared/references/heartbeat-checkin-discipline.md" "Portfolio 'NOTIFY' check-ins should include 'CTO intervention'" "heartbeat CTO intervention reporting"
require_text "shared/references/heartbeat-checkin-discipline.md" "A release blocker gets one non-material heartbeat" "heartbeat release blocker intervention trigger"
require_text "shared/references/heartbeat-checkin-discipline.md" 'empty completed turn or `systemError`' "heartbeat empty turn intervention trigger"
require_text "shared/references/heartbeat-checkin-discipline.md" "wrong path/base/model lane" "heartbeat wrong path base model trigger"
require_text "shared/references/heartbeat-checkin-discipline.md" "intervene immediately" "CTO proactive intervention rule"
require_text "shared/references/delegation-protocol.md" "Prefer multi-agent/subagent delegation" "prefer internal subagent delegation"
require_text "shared/references/delegation-protocol.md" "Never archive user-created control or skill threads" "do not archive owner control threads"
require_text "shared/references/delegation-protocol.md" "Missing delegation after strategy" "delegation self-improvement classification"
require_text "shared/references/delegation-protocol.md" "Thread Boundary" "delegation thread boundary"
require_text "shared/references/delegation-protocol.md" 'Issue branch name and PR base; never direct `main`' "worker branch/base guard"
require_text "shared/references/delegation-protocol.md" "protected archive" "worker protected archive guard"
require_text "shared/references/delegation-protocol.md" 'Look for `list_projects`, `create_thread`, `fork_thread`, `send_message_to_thread`' "delegation tool discovery requirement"
require_text "shared/references/delegation-protocol.md" "Worktree Creation Guard" "delegation worktree creation guard section"
require_text "shared/references/delegation-protocol.md" 'git rev-parse --show-toplevel' "delegation repo-root verification command"
require_text "shared/references/delegation-protocol.md" "Exact-project preflight" "delegation exact project preflight"
require_text "shared/references/delegation-protocol.md" "setup-blocked: missing exact repo project" "delegation missing repo project blocker"
require_text "shared/references/delegation-protocol.md" 'Do not create issue/worktree checkouts directly as visible plugin folders under `wp-content/plugins`' "delegation visible plugin folder guard"
require_text "shared/references/delegation-protocol.md" "keep exactly one visible canonical plugin folder per product per instance" "delegation canonical plugin folder rule"
require_text "shared/references/delegation-protocol.md" "unusable worktree" "delegation unusable worktree classification"
require_text "shared/references/delegation-protocol.md" "Worktree Hygiene" "delegation worktree hygiene section"
require_text "shared/references/repo-product-docs-contract.md" '`TESTING.md`' "repo docs testing doc support"
require_text "shared/references/repo-product-docs-contract.md" '`PLAYGROUND.md`' "repo docs playground doc support"
require_text "shared/references/repo-product-docs-contract.md" "audit active products for missing, weak, or stale" "repo docs audit rule"
require_text "shared/references/repo-product-docs-contract.md" "cross-product orchestration rules belong in the WP Expert skills" "repo docs boundary rule"
require_text "shared/references/repo-product-docs-contract.md" "before screenshots" "repo docs issue screenshot rule"
require_text "shared/references/self-improvement-loop.md" 'Empty completed or `systemError` turn.' "self-improvement empty turn class"
require_text "shared/references/self-improvement-loop.md" "Wrong model or reasoning allocation." "self-improvement wrong model class"
require_text "shared/references/self-improvement-loop.md" "Missing issue or PR proof." "self-improvement missing proof class"
require_text "shared/references/self-improvement-loop.md" "Repeated owner-instruction drift." "self-improvement owner instruction class"
require_text "shared/references/authority-growth-lane.md" "This is not generic blog writing." "authority growth non-generic rule"
require_text "shared/references/authority-growth-lane.md" "evidence-backed growth work" "authority growth evidence rule"
require_text "shared/references/authority-growth-lane.md" "do not promise traffic, rankings, or citations" "authority growth no unsupported claims"
require_text "shared/references/delegation-protocol.md" 'git worktree list --porcelain' "delegation worktree inventory command"
require_text "skill-evals/wp-product-orchestrator-scenarios.md" "active/prunable metadata/stale-clean/dirty-owner states" "delegation worktree eval classification"
require_text "shared/references/delegation-protocol.md" 'git worktree remove <path>' "delegation safe worktree removal command"
require_text "shared/references/delegation-protocol.md" 'git worktree prune' "delegation worktree prune command"
require_text "shared/references/delegation-protocol.md" "Never remove a worktree that is dirty" "delegation dirty worktree preservation"
require_text "shared/references/delegation-protocol.md" "screenshot/proof notes only for the UI-visible state change" "delegation cleanup proof scope"
require_text "shared/references/delegation-protocol.md" "Unblock-First Recovery Ladder" "delegation unblock-first recovery ladder"
require_text "shared/references/delegation-protocol.md" "Research, GitHub issue intake, support/forum triage" "delegation direct non-code work path"
require_text "shared/references/delegation-protocol.md" "Read-only code mapping or evidence" "delegation read-only mapping path"
require_text "shared/references/delegation-protocol.md" 'manual `git worktree`' "delegation manual git worktree recovery"
require_text "shared/references/delegation-protocol.md" "Notify the owner only when the remaining action is owner-only" "delegation owner-only notification gate"
require_text "shared/references/delegation-protocol.md" "Recovered by doing Y; next work is Z" "delegation recovered final status"
require_text "shared/references/delegation-protocol.md" "Stale active turn handling" "delegation stale active turn handling"
require_text "shared/references/delegation-protocol.md" "Dirty or behind primary checkouts block direct edits there." "delegation dirty primary checkout rule"
require_text "shared/references/delegation-protocol.md" "explicit branch-model conflict" "delegation explicit branch-model blocker"
require_text "shared/references/release-train-discipline.md" "Do not create a next milestone prerelease" "release train production gate"
require_text "shared/references/rolling-milestone-triage.md" "3-4 calendar days" "post-release patch timing"
require_text "shared/references/rolling-milestone-triage.md" "15 calendar days" "post-release minor major timing"
require_text "shared/references/release-train-discipline.md" "At T-1" "release scope freeze"
require_text "shared/references/release-train-discipline.md" "exact version and candidate SHA" "exact beta approval"
require_text "shared/references/release-train-discipline.md" "Implemented-proof-gap" "post-release issue taxonomy"
require_text "shared/references/release-train-discipline.md" "four working hours" "production regression escalation"
require_text "shared/references/commit-pr-discipline.md" 'Partial work uses `Related`' "partial issue relation semantics"
require_text "shared/references/release-train-discipline.md" "Milestones need due dates" "milestone due-date reference rule"
require_text "shared/references/release-train-discipline.md" '`main` is production release space only' "main production-only rule"
require_text "shared/references/release-train-discipline.md" "Main-First Production Release Transaction" "main-first production transaction"
require_text "shared/references/release-train-discipline.md" "Production Mainline Reconciliation" "production mainline recovery section"
require_text "shared/references/release-train-discipline.md" 'exact release tag is an ancestor of `origin/main`' "production mainline tag-ancestry gate"
require_text "shared/references/release-train-discipline.md" 'merge the approved release PR into `main` before creating the stable tag or GitHub release' "production merge-before-release gate"
require_text "shared/references/release-train-discipline.md" 'gh release create <tag> --verify-tag' "verified existing release tag"
require_text "shared/references/release-train-discipline.md" 'Do not use `--target release/*`' "no production release-branch target"
require_text "shared/references/release-train-discipline.md" "Forward-sync" "post-release forward sync"
require_text "shared/references/release-train-discipline.md" "already-published off-main release" "off-main release recovery"
require_text "shared/references/release-train-discipline.md" "squash, rebase, or cherry-pick recovery does not satisfy tag ancestry" "ancestry-preserving recovery merge"
require_text "shared/references/release-train-discipline.md" "Release Automation Contract" "release automation contract"
require_text "wp-product-orchestrator/scripts/release-mainline-audit.sh" 'git merge-base --is-ancestor' "deterministic mainline ancestry helper"
require_text "shared/references/repo-product-docs-contract.md" "main-first production merge/tag/release sequence" "repo release mainline contract"
require_text "wp-product-orchestrator/SKILL.md" "Production is main-first" "product main-first hot path"
require_text "wp-portfolio-cto/SKILL.md" 'production tag not reachable from `main`' "portfolio mainline drift trigger"
require_text "shared/references/release-train-discipline.md" "owner testing confirmation" "owner testing release readiness"
require_text "shared/references/release-train-discipline.md" "live-verified release target" "release WordPress tested up metadata"
require_text "shared/references/release-train-discipline.md" "missing due date alone" "release missing due date not blocker"
require_text "shared/references/release-train-discipline.md" 'Milestone release work must target `release/<release-version>`' "release version branch required"
require_text "shared/references/release-train-discipline.md" "not the GitHub milestone ID or sequence number" "release no milestone ID branch"
require_text "shared/references/release-train-discipline.md" "wrong milestone-ID branch" "release wrong branch recovery"
require_text "shared/references/release-train-discipline.md" "Normal product orchestration, issue intake, implementation, hardening PRs" "release normal work no approval"
require_text "shared/references/release-train-discipline.md" "good non-production PR review/merge" "release non-production PR autonomy"
require_text "shared/references/release-train-discipline.md" "When the train is release-ready" "release-ready notification rule"
require_text "shared/references/release-train-discipline.md" "Release-ready recommendations and owner approval requests require fresh live verification" "release live verification required"
require_text "shared/references/release-train-discipline.md" "do not request beta/production approval" "release live verification fail closed"
require_text "shared/references/release-train-discipline.md" "release metadata matches the target version" "release metadata match gate"
require_text "shared/references/release-train-discipline.md" "plugin header/version file" "release metadata surfaces"
require_text "shared/references/release-train-discipline.md" '`readme.txt` and changelog/release notes are release-current' "release readme changelog audit gate"
require_text "shared/references/release-train-discipline.md" "upgrade notice when applicable" "release upgrade notice audit"
require_text "shared/references/release-train-discipline.md" "no overclaiming unmerged future milestone work" "release overclaim prevention"
require_text "shared/references/release-train-discipline.md" 'focused release-readiness issue/PR against the active `release/<version>` branch' "release readiness PR branch gate"
require_text "shared/references/release-train-discipline.md" "include explicit readme/changelog audit evidence" "release readme evidence brief"
require_text "shared/references/release-train-discipline.md" "Package/readme/Plugin Check validation is not current" "release plugin check blocker"
require_text "shared/references/release-train-discipline.md" "focused release-readiness issue/PR" "release metadata/readme blocker PR"
require_text "shared/references/release-train-discipline.md" "release-candidate visual proof from the packaged ZIP/build" "release candidate visual proof gate"
require_text "shared/references/release-train-discipline.md" "golden workflow regression matrix" "release golden workflow matrix gate"
require_text "shared/references/release-train-discipline.md" "package/build used, exact environment, visual proof status" "release-ready proof detail"
require_text "shared/references/release-train-discipline.md" "Release Quality Gate Matrix" "release quality gate matrix section"
require_text "shared/references/release-train-discipline.md" "Security/privacy: capabilities, nonces/auth, sanitization/escaping" "release security matrix gate"
require_text "shared/references/release-train-discipline.md" "Performance: admin/frontend load, queries, assets/enqueues" "release performance matrix gate"
require_text "shared/references/release-train-discipline.md" "Commented-code/dead-code hygiene" "release hygiene matrix gate"
require_text "shared/references/release-train-discipline.md" '`Not applicable - reason`' "release non-applicable gate reason"
require_text "shared/references/release-train-discipline.md" "compact quality gate matrix" "release-ready brief matrix summary"
require_text "shared/references/rolling-milestone-triage.md" "Current train" "rolling milestone current train"
require_text "shared/references/rolling-milestone-triage.md" "Next train" "rolling milestone next train"
require_text "shared/references/rolling-milestone-triage.md" "Horizon train" "rolling milestone horizon train"
require_text "shared/references/rolling-milestone-triage.md" "Patch/hotfix train" "rolling milestone patch train"
require_text "shared/references/rolling-milestone-triage.md" "Patch/hotfix train: regressions, security/privacy fixes, support escalations, release blockers" "rolling milestone patch issue routing"
require_text "shared/references/rolling-milestone-triage.md" "Minor train" "rolling milestone minor train"
require_text "shared/references/rolling-milestone-triage.md" "Major train" "rolling milestone major train"
require_text "shared/references/rolling-milestone-triage.md" "Research lane" "rolling milestone research lane"
require_text "shared/references/rolling-milestone-triage.md" "Keep 2-3 upcoming milestone trains triaged" "rolling milestone future train planning"
require_text "shared/references/rolling-milestone-triage.md" "too many untriaged issues" "rolling milestone CTO health signal"
require_text "shared/references/product-queue-triage.md" "rolling-milestone-triage.md" "queue rolling milestone routing"
require_text "shared/references/github-communication-protocol.md" "GitHub Issue And PR Comments" "GitHub issue and PR comments protocol"
require_text "shared/references/github-communication-protocol.md" "Label-Driven Ready State" "GitHub label-driven ready state"
require_text "shared/references/github-communication-protocol.md" '`owner:codex`: ready for Codex/orchestrator/worker action' "GitHub owner:codex ready label"
require_text "shared/references/github-communication-protocol.md" '`owner:me`: waiting on `@mehul0810` for true hard gates' "GitHub owner:me hard gate label"
require_text "shared/references/github-communication-protocol.md" "reversible and non-release" "GitHub owner:me reversible autonomy"
require_text "shared/references/github-communication-protocol.md" 'Do not require owner comments to start with `Codex:`' "GitHub no Codex prefix dependency"
require_text "shared/references/github-communication-protocol.md" 'relabels `owner:codex`' "GitHub resume after relabel"
require_text "shared/references/github-communication-protocol.md" "Write GitHub comments sparingly" "quiet GitHub write discipline"
require_text "shared/references/github-communication-protocol.md" "Do not post GitHub comments for routine notifications" "no routine GitHub notification comments"
require_text "shared/references/github-communication-protocol.md" "CTO control chat thread" "routine status routes to CTO chat"
require_text "shared/references/commit-pr-discipline.md" "type(scope): concise action" "commit convention"
require_text "shared/references/commit-pr-discipline.md" "Every PR must include" "PR template requirements"
require_text "shared/references/commit-pr-discipline.md" "Screenshot evidence for admin, editor, frontend, style, layout, UX" "PR screenshot evidence requirement"
require_text "shared/references/commit-pr-discipline.md" 'Product repositories keep `main` as production release space' "commit-pr main production-only rule"
require_text "shared/references/commit-pr-discipline.md" "Worker PR Rule" "worker one issue one PR rule"
require_text "shared/references/commit-pr-discipline.md" "verified development base" "commit-pr verified development base"
require_text "shared/references/commit-pr-discipline.md" 'Milestone-based work must create or use `release/<release-version>`' "commit-pr release-version branch required"
require_text "shared/references/commit-pr-discipline.md" "not the GitHub milestone ID or sequence number" "commit-pr no milestone ID branch"
require_text "shared/references/commit-pr-discipline.md" "retarget open PRs" "commit-pr wrong branch recovery"
require_text "shared/references/commit-pr-discipline.md" '`develop` is for unmilestoned development integration' "commit-pr develop unmilestoned rule"
require_text "shared/references/commit-pr-discipline.md" "Non-Production Merge Rule" "commit-pr non-production merge rule"
require_text "shared/references/commit-pr-discipline.md" "no explicit current owner stop exists on that exact PR" "commit-pr owner stop check"
require_text "shared/references/commit-pr-discipline.md" "report the exact blocker instead of treating it as an owner decision" "commit-pr tooling blocker classification"
require_text "shared/references/product-autonomy-permissions.md" "critical, destructive, transfer, uncertain-side-effect, and approval-bypass actions" "autonomy command approval boundary"
require_text "shared/references/product-autonomy-permissions.md" 'do not stall on `owner:me`' "autonomy owner:me no stall"
require_text "shared/references/product-autonomy-permissions.md" "If the owner is unavailable and the blocker is non-destructive, local, reversible, and outside the hard-gate list" "autonomy owner unavailable active unblock"
require_text "shared/references/product-autonomy-permissions.md" "PR review/merge for good non-production PRs" "autonomy non-production PR merge"
require_text "shared/references/product-autonomy-permissions.md" "Review and merge safe non-production PRs" "autonomy safe non-production merge rule"
require_text "shared/references/product-autonomy-permissions.md" "report the exact tooling or approval-layer blocker" "autonomy merge tooling blocker"
require_text "shared/references/product-autonomy-permissions.md" "Security-sensitive findings should not become public issues" "autonomy sanitized security rule"
require_text "shared/references/product-queue-triage.md" "Product-idea issues require web research" "product idea web research rule"
require_text "shared/references/community-intake-hygiene.md" 'Treat human contributor PRs as a first-class intake lane: PRs opened by someone other than `@mehul0810` or automation/bots' "queue human contributor PR lane"
require_text "shared/references/community-intake-hygiene.md" 'Treat new human-created issues as a first-class community issue intake lane: issues opened by someone other than `@mehul0810` or automation/bots' "queue human-created issue lane"
require_text "shared/references/product-queue-triage.md" "product-thread objective is release readiness" "queue release-readiness objective"
require_text "shared/references/product-queue-triage.md" 'Assign to `@mehul0810`' "product issue assignee rule"
require_text "shared/references/product-queue-triage.md" "Competitor names may inform private research" "product issue competitor-neutral rule"
require_text "shared/references/product-queue-triage.md" "Owner-mentioned work is approved intake signal, not an owner-decision blocker" "queue owner-mentioned approved intake"
require_text "shared/references/product-queue-triage.md" "Do not blindly drain every issue in a milestone" "queue milestone scope gate"
require_text "shared/references/product-queue-triage.md" "define the milestone/release scope and priority set" "queue release scope priority gate"
require_text "shared/references/product-queue-triage.md" 'Ensure `owner:codex` and `owner:me` labels exist' "queue ensure owner labels"
require_text "shared/references/product-queue-triage.md" '`owner:me` is not a stall for reversible non-release choices' "queue owner:me reversible autonomy"
require_text "shared/references/product-queue-triage.md" "current milestone has no ready work" "queue next milestone fallback"
require_text "shared/references/product-queue-triage.md" "create proactive review work" "queue proactive review work"
require_text "shared/references/product-queue-triage.md" "sanitized hardening, or authority/growth" "queue proactive ecosystem review"
require_text "shared/references/product-queue-triage.md" "Convert real discoveries into issues unless they are safely fixed inside the current PR scope" "queue discovery issue conversion"
require_text "shared/references/product-queue-triage.md" "observed symptom, why it matters, suspected source, affected files/surfaces, acceptance criteria, validation/proof expectation, risk, and whether docs need updating" "queue discovery issue fields"
require_text "shared/references/product-queue-triage.md" "blocker, near-term improvement, research-needed idea, or owner-gated strategic choice" "queue discovery classification"
require_text "shared/references/product-queue-triage.md" 'live-verified `Tested up to` target' "queue WordPress tested up metadata"
require_text "shared/references/product-queue-triage.md" "Security-sensitive findings must not become public issues" "queue sanitized security issue rule"
require_text "shared/references/product-queue-triage.md" 'resume when answered and relabeled `owner:codex`' "queue resume after owner relabel"
require_text "shared/references/product-queue-triage.md" "nearest appropriate milestone or release train among the next three" "queue next-three milestone prioritization"
require_text "shared/references/product-queue-triage.md" "Missing milestone due dates or branch-policy gaps are not blanket blockers for owner-approved intake" "queue owner-approved intake metadata blocker"
require_text "shared/references/product-queue-triage.md" "production/beta release action" "queue owner decision hard-gate scope"
require_text "shared/references/product-queue-triage.md" "Design Contract Intake" "queue design contract intake"
require_text "shared/references/product-queue-triage.md" 'Create focused GitHub issues to add or adapt `DESIGN.md`' "queue design issue rule"
require_text "shared/references/product-queue-triage.md" "State accountable role, control/proof gap, failure behavior, and screenshot evidence" "queue enterprise design issue framing"
require_text "shared/references/product-queue-triage.md" 'Do not merge Dependabot or dependency PRs directly into `main`' "queue no dependabot main merge"
require_text "shared/references/product-queue-triage.md" "Consolidate relevant dependency/tooling updates into one duplicate-screened GitHub issue" "queue dependency consolidation"
require_text "shared/references/product-queue-triage.md" "close with a durable GitHub comment" "queue stale PR durable closure comment"
require_text "shared/references/product-queue-triage.md" "checking comments, reviews, labels, and milestones first" "queue stale PR evidence guard"
require_text "shared/references/product-queue-triage.md" "not blanket blockers for owner-approved intake" "queue due date blocker discipline"
require_text "shared/references/product-queue-triage.md" 'Milestone work must use `release/<release-version>` as branch and PR base' "queue release-version branch required"
require_text "shared/references/product-queue-triage.md" "not the GitHub milestone ID or sequence number" "queue no milestone ID branch"
require_text "shared/references/product-queue-triage.md" "wrong milestone-ID branch" "queue wrong branch recovery"
require_text "shared/references/product-queue-triage.md" "fresh scoped worktree delegation" "queue dirty checkout worktree delegation"
require_text "shared/references/product-queue-triage.md" "Release-Ready Notification" "queue release-ready notification section"
require_text "shared/references/product-queue-triage.md" "retry once for the missing signal" "queue bounded live retry"
require_text "shared/references/product-queue-triage.md" "use local remote-tracking and repo evidence only for non-mutating summary" "queue fallback non-mutating summary"
require_text "shared/references/product-queue-triage.md" "Do not create issues, relabel, merge, delegate" "queue no mutation without live labels"
require_text "shared/references/product-queue-triage.md" "Merged PRs and included scope" "queue release-ready merged PR evidence"
require_text "shared/references/product-queue-triage.md" "Release metadata match for target version" "queue release metadata status"
require_text "shared/references/product-queue-triage.md" "Readme/changelog audit" "queue readme changelog audit"
require_text "shared/references/community-intake-hygiene.md" "Acknowledge human contributor PRs within 24 hours when feasible" "queue contributor ack window"
require_text "shared/references/community-intake-hygiene.md" "Do not close immediately unless spam, malicious/unsafe, unrelated, clearly invalid" "queue contributor no immediate close"
require_text "shared/references/community-intake-hygiene.md" "Wait 2 business days after the initial review" "queue contributor first wait cycle"
require_text "shared/references/community-intake-hygiene.md" "Wait 2 more business days after follow-up" "queue contributor second wait cycle"
require_text "shared/references/community-intake-hygiene.md" "preserve credit with co-author attribution or explicit credit" "queue contributor credit preservation"
require_text "shared/references/community-intake-hygiene.md" "Acknowledge new external issues within 24 hours when feasible" "queue external issue ack window"
require_text "shared/references/community-intake-hygiene.md" "Initial triage should classify: confirmed bug, needs reproduction, feature request, support/question, documentation gap, duplicate, security/private, or not planned/out of scope" "queue external issue triage classes"
require_text "shared/references/community-intake-hygiene.md" "Wait 2 business days after asking for info" "queue external issue first wait cycle"
require_text "shared/references/community-intake-hygiene.md" "Wait 2 more business days after follow-up" "queue external issue second wait cycle"
require_text "shared/references/community-intake-hygiene.md" "move to a private/security process; do not ask for secrets publicly" "queue external issue private security handling"
require_text "shared/references/community-intake-hygiene.md" "close with thanks, release/version reference, and any verification steps" "queue external issue owner-readable closure"
require_text "shared/references/community-intake-hygiene.md" "Prefer GitHub Issue Forms YAML for structured issue intake where practical" "queue AI-friendly issue forms"
require_text "shared/references/community-intake-hygiene.md" "summary, linked issue, scope, implementation notes, screenshots/UI proof, validation run" "queue AI-friendly PR template"
require_text "shared/references/community-intake-hygiene.md" "creates or updates a WordPress Playground test link" "queue Playground preview support"
require_text "shared/references/community-intake-hygiene.md" "updated, not spammed" "queue Playground update not spam"
require_text "shared/references/community-intake-hygiene.md" "packaged artifact or zip" "queue Playground packaged artifact caveat"
require_text "shared/references/community-intake-hygiene.md" "must not expose secrets" "queue Playground no secrets"
require_text "shared/references/community-intake-hygiene.md" "Contributor PRs should also get the Playground link" "queue contributor Playground support"
require_text "shared/references/community-intake-hygiene.md" "missing Playground or equivalent visual/browser proof as a readiness gap" "queue Playground readiness gap"
require_text "shared/references/heartbeat-checkin-discipline.md" "Community queues" "heartbeat community queues section"
require_text "shared/references/heartbeat-checkin-discipline.md" "Open human contributor PRs or new human-created issues are ignored in quiet-state reporting" "heartbeat community quiet-state challenge"
require_text "shared/references/heartbeat-checkin-discipline.md" "A UI/user-workflow PR is treated as ready without Playground or equivalent visual/browser proof" "heartbeat Playground readiness challenge"
require_text "shared/references/heartbeat-checkin-discipline.md" "Unexpected behavior, maintainability debt, weak non-obvious comments, missing test coverage, repeated validation/tooling surprises, or workflow friction are reported without creating or linking a focused issue" "heartbeat adjacent finding issue challenge"
require_text "shared/references/heartbeat-checkin-discipline.md" "human contributor PR queue" "heartbeat product human contributor queue"
require_text "shared/references/heartbeat-checkin-discipline.md" "human-created issue queue" "heartbeat product human issue queue"
require_text "shared/references/github-communication-protocol.md" "Contributor And Community Courtesy" "GitHub contributor courtesy section"
require_text "shared/references/github-communication-protocol.md" "For contributor/community closures, comments should be owner-readable" "GitHub contributor closure readability"
require_text "shared/references/github-communication-protocol.md" "clear canonical issue/PR link and thanks" "GitHub duplicate courtesy close"
require_text "shared/references/github-communication-protocol.md" "Playground Preview Comments" "GitHub Playground comment section"
require_text "shared/references/github-communication-protocol.md" "Update the existing Playground preview comment" "GitHub Playground update not spam"
require_text "shared/references/github-communication-protocol.md" "Never expose secrets, private tokens, production credentials" "GitHub Playground no secrets"
require_text "shared/references/live-proof-wordpress.md" "Design-Visible PR Screenshot Rule" "live proof design-visible screenshot rule"
require_text "shared/references/live-proof-wordpress.md" "Release Candidate Visual Proof" "live proof release candidate visual proof"
require_text "shared/references/live-proof-wordpress.md" "test the release-candidate package/ZIP or release branch build" "live proof package build requirement"
require_text "shared/references/live-proof-wordpress.md" "Golden Workflow Regression Matrix" "live proof golden workflow matrix"
require_text "shared/references/live-proof-wordpress.md" "desktop and narrow/mobile/admin-constrained widths" "live proof responsive screenshot widths"
require_text "shared/references/live-proof-wordpress.md" '`wp-proof`' "live proof wp-proof preference"
require_text "skill-evals/wp-product-orchestrator-scenarios.md" "Bounded live check" "bounded live check eval scenario"
require_text "skill-evals/wp-product-orchestrator-scenarios.md" "Heartbeat partial exit" "heartbeat partial exit eval scenario"
require_text "skill-evals/wp-product-orchestrator-scenarios.md" "Broken layout release prevention" "release visual regression eval scenario"
require_text "skill-evals/wp-product-orchestrator-scenarios.md" "Stale release metadata" "release metadata eval scenario"
require_text "skill-evals/wp-product-orchestrator-scenarios.md" "Readme changelog release gate" "readme changelog release eval scenario"
require_text "skill-evals/wp-product-orchestrator-scenarios.md" "Production mainline reconciliation" "production mainline reconciliation eval scenario"
require_text "skill-evals/wp-product-orchestrator-scenarios.md" "Main-first production release" "main-first release eval scenario"
require_text "skill-evals/wp-product-orchestrator-scenarios.md" "Unsafe release automation" "unsafe release workflow eval scenario"
require_text "skill-evals/wp-product-orchestrator-scenarios.md" "Safe non-production PR merge" "safe non-production merge eval scenario"
require_text "skill-evals/wp-product-orchestrator-scenarios.md" "Worker Threads execution room" "worker-threads eval scenario"
require_text "shared/references/weekly-wordpress-intelligence.md" "Weekly WordPress Ecosystem Intelligence" "weekly WordPress ecosystem intelligence"
require_text "shared/references/self-improvement-loop.md" "Self-Improvement Loop" "self-improvement loop"
require_text "shared/references/self-improvement-loop.md" "Stale Learning Lifecycle" "self-improvement stale learning lifecycle"
require_text "shared/references/self-improvement-loop.md" "Durable Artifact Dedupe" "self-improvement durable artifact dedupe"
require_text "shared/references/self-improvement-loop.md" "Closed Feedback And Outcome Lineage" "self-improvement closed feedback contract"
require_text "shared/references/self-improvement-loop.md" "observation -> evidence -> decision -> action -> verification -> outcome -> durable artifact" "self-improvement lineage chain"
require_text "shared/references/self-improvement-loop.md" 'Issue creation, merge, release, or passing checks are delivery evidence, not outcome proof.' "self-improvement outcome proof boundary"
require_text "skill-evals/wp-product-orchestrator-scenarios.md" "Closed feedback" "product closed-feedback scenario"
require_text "skill-evals/wp-portfolio-cto-scenarios.md" "Cross-product learning" "CTO cross-product learning scenario"
require_text "shared/references/self-improvement-loop.md" "Supersede note created" "self-improvement stale outcome labels"
require_text "shared/references/self-improvement-loop.md" "Open PRs and issues" "self-improvement duplicate artifact checks"
require_text "shared/references/self-improvement-loop.md" "Missing delegation after strategy" "self-improvement missing delegation label"
require_text "shared/references/self-improvement-loop.md" "Portfolio coverage drift" "self-improvement portfolio drift label"
require_text "shared/references/self-improvement-loop.md" "Portfolio execution drift" "self-improvement portfolio execution label"
require_text "shared/references/self-improvement-loop.md" "Product thread topology drift" "self-improvement topology drift label"
require_text "shared/references/self-improvement-loop.md" "Delegation unavailable without tool discovery" "self-improvement tool discovery label"
require_text "shared/references/self-improvement-loop.md" "Setup-blocked polling loop" "self-improvement setup-blocked polling label"
require_text "shared/references/self-improvement-loop.md" "Stale active product thread" "self-improvement stale active thread label"
require_text "shared/references/self-improvement-loop.md" "Blanket blocker from due date, release branch, or dirty primary checkout" "self-improvement blanket blocker label"
require_text "shared/references/self-improvement-loop.md" "Stale Learning Lifecycle" "self-improvement stale-learning lifecycle section"
require_text "shared/references/self-improvement-loop.md" "Add" "self-improvement add lifecycle outcome"
require_text "shared/references/self-improvement-loop.md" "Correct" "self-improvement correct lifecycle outcome"
require_text "shared/references/self-improvement-loop.md" "Retire" "self-improvement retire lifecycle outcome"
require_text "shared/references/self-improvement-loop.md" "Supersede" "self-improvement supersede lifecycle outcome"
require_text "shared/references/self-improvement-loop.md" "Keep Watching" "self-improvement keep-watching lifecycle outcome"
require_text "shared/references/self-improvement-loop.md" "Ignore" "self-improvement ignore lifecycle outcome"
require_text "shared/references/self-improvement-loop.md" "Fixed now" "self-improvement fixed-now audit outcome"
require_text "shared/references/self-improvement-loop.md" "PR opened" "self-improvement PR-opened audit outcome"
require_text "shared/references/self-improvement-loop.md" "Supersede note created" "self-improvement supersede-note-created audit outcome"
require_text "shared/references/self-improvement-loop.md" "Detected only" "self-improvement detected-only audit outcome"
require_text "shared/references/self-improvement-loop.md" "Duplicate durable artifact" "self-improvement duplicate artifact label"
require_text "shared/references/self-improvement-loop.md" "Stale local-ref conclusion" "self-improvement stale local-ref label"
require_text "shared/references/self-improvement-loop.md" "Unclassified stale learning" "self-improvement unclassified stale learning label"
require_text "shared/references/self-improvement-loop.md" "Durable Artifact Dedupe" "self-improvement durable artifact dedupe section"
require_text "shared/references/self-improvement-loop.md" "Normalized rule slug" "self-improvement normalized slug dedupe"
require_text "shared/references/self-improvement-loop.md" "Normalized automation name, prompt intent, schedule, cwd/target, and active status" "self-improvement automation dedupe keys"
require_text "shared/references/self-improvement-loop.md" "Duplicate recurring automation" "self-improvement duplicate automation label"
require_text "shared/references/self-improvement-loop.md" "Open PRs and issues" "self-improvement open PR/issue dedupe"
require_text "shared/references/self-improvement-loop.md" "Recently merged PRs and closed issues" "self-improvement merged PR/closed issue dedupe"
require_text "shared/references/self-improvement-loop.md" "one compact rollup per date" "self-improvement same-day rollup dedupe"
require_text "shared/references/self-improvement-loop.md" "report the duplicate automation IDs for cleanup" "self-improvement duplicate automation cleanup reporting"
require_text "shared/references/disposable-proof-environment-lifecycle.md" "Never delete a Studio site based on its name" "proof-environment no-name deletion guard"
require_text "shared/references/disposable-proof-environment-lifecycle.md" "Without a live owner-approved lifecycle policy and policy-gated adapter, do not create or delete" "proof-environment live policy gate"
require_text "shared/references/disposable-proof-environment-lifecycle.md" "Expiry is a stale-resource review trigger, not deletion permission" "proof-environment expiry semantics"
require_text "shared/references/disposable-proof-environment-lifecycle.md" "registry and on-disk manifest disagree" "proof-environment manifest match guard"
require_text "shared/references/disposable-proof-environment-lifecycle.md" "Loop Steward reports lifecycle drift but does not delete product proof sites." "proof-environment stewardship boundary"
require_absent "shared/references/disposable-proof-environment-lifecycle.md" "proof-environment-policy.json" "proof-environment reference has no nonexistent policy path"
require_text "skill-evals/wp-product-orchestrator-scenarios.md" "expiry as review evidence, not deletion permission" "proof-environment expiry eval"
require_text "shared/references/repo-product-docs-contract.md" "Product Truth Does Not Live Only In The Skill" "repo product docs contract"
require_text "shared/references/repo-product-docs-contract.md" '`DESIGN.md`: concise product design contract' "repo DESIGN.md product design contract"
require_text "shared/references/repo-product-docs-contract.md" "not a heavy design-system spec" "repo DESIGN.md not heavy spec"
require_text "shared/references/repo-product-docs-contract.md" "duplicate-screened product issues" "repo DESIGN.md duplicate-screened issue rule"
require_text "shared/references/repo-product-docs-contract.md" "active UI drift, onboarding risk, or an upcoming design-heavy train" "repo DESIGN.md product priority"
require_text "shared/references/repo-product-docs-contract.md" "WordPress Design System" "repo design-system baseline"
require_text "shared/references/repo-product-docs-contract.md" "brand colors" "repo brand-color layering rule"
require_text "shared/references/repo-product-docs-contract.md" 'audit active products for missing, weak, or stale `AGENTS.md`, `DESIGN.md`, `TESTING.md`, and `RELEASE.md` guidance' "repo active-product doc audit rule"
require_text "shared/references/repo-product-docs-contract.md" "Create focused GitHub issues instead of relying on chat instructions" "repo docs issue-not-chat rule"
require_text "shared/references/repo-product-docs-contract.md" "Treat product docs as self-improving, not one-time setup" "repo self-improving docs rule"
require_text "shared/references/repo-product-docs-contract.md" "Unexpected behavior, maintainability debt, weak non-obvious comments, missing test coverage, repeated validation/tooling surprises, or workflow friction teaches a reusable product-specific rule" "repo reusable lesson doc update rule"
require_text "shared/references/adjacent-finding-protocol.md" "weak comments around non-obvious logic" "adjacent weak comments coverage"
require_text "shared/references/adjacent-finding-protocol.md" "Create a focused GitHub issue for any unexpected behavior, code smell, maintainability debt, weak non-obvious comments, missing test coverage, repeated validation/tooling surprise, or workflow friction unless it was fixed inside the current PR scope" "adjacent focused issue rule"
require_text "shared/references/adjacent-finding-protocol.md" "Use issue fields: observed symptom, why it matters, suspected source, affected files/surfaces, acceptance criteria, validation/proof expectation, risk, and whether docs need updating" "adjacent issue fields rule"

if [ "$errors" -gt 0 ]; then
  echo "orchestration behavior audit failed: $errors missing guardrail(s)" >&2
  exit 1
fi

echo "orchestration behavior audit passed"
