#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
errors=0

require_text() {
  local file="$1"
  local text="$2"
  local label="$3"

  if grep -Fq "$text" "$repo_root/$file"; then
    echo "ok: $label"
  else
    echo "missing: $label ($file)" >&2
    errors=$((errors + 1))
  fi
}

require_file() {
  local file="$1"
  local label="$2"

  if [ -f "$repo_root/$file" ]; then
    echo "ok: $label"
  else
    echo "missing: $label ($file)" >&2
    errors=$((errors + 1))
  fi
}

require_file "shared/references/cto-orchestration-operating-model.md" "CTO operating model reference"
require_file "shared/references/delegation-protocol.md" "delegation protocol reference"
require_file "shared/references/release-train-discipline.md" "release train discipline reference"
require_file "shared/references/github-communication-protocol.md" "GitHub communication protocol reference"
require_file "shared/references/commit-pr-discipline.md" "commit and PR discipline reference"
require_file "shared/references/weekly-wordpress-intelligence.md" "weekly WordPress intelligence reference"
require_file "shared/references/self-improvement-loop.md" "self-improvement loop reference"
require_file "shared/references/repo-product-docs-contract.md" "repo product docs contract reference"

require_text "wp-product-orchestrator/SKILL.md" "CTO control-plane" "orchestrator CTO control-plane language"
require_text "wp-product-orchestrator/SKILL.md" "GitHub issue-first" "orchestrator GitHub issue-first routing"
require_text "wp-product-orchestrator/SKILL.md" "Plan before delegation" "orchestrator plan-before-delegation rule"
require_text "wp-product-orchestrator/SKILL.md" "source of truth hierarchy" "orchestrator source-of-truth hierarchy"
require_text "wp-product-orchestrator/SKILL.md" "Do not create a next milestone prerelease" "orchestrator release train prerelease gate"
require_text "wp-product-orchestrator/SKILL.md" "Milestones need due dates" "orchestrator milestone due-date rule"
require_text "wp-product-orchestrator/SKILL.md" "Codex:" "orchestrator owner-authored Codex instructions"
require_text "wp-product-orchestrator/SKILL.md" "Do not post GitHub comments for routine notifications" "orchestrator quiet GitHub comment discipline"
require_text "wp-product-orchestrator/SKILL.md" "CTO control chat thread" "orchestrator CTO chat status routing"
require_text "wp-product-orchestrator/SKILL.md" "Keep direct CTO execution limited" "orchestrator direct execution boundary"
require_text "wp-product-orchestrator/SKILL.md" "delegate at least one bounded task" "orchestrator mandatory delegation trigger"
require_text "wp-product-orchestrator/SKILL.md" "Delegation decision" "orchestrator delegation decision status line"
require_text "wp-product-orchestrator/SKILL.md" "portfolio-wide sweep across all assigned products" "orchestrator portfolio sweep"
require_text "wp-product-orchestrator/SKILL.md" "No action after verification" "orchestrator quiet product reporting"
require_text "wp-product-orchestrator/SKILL.md" "Aculect AI Companion, WP Distraction Free View, OneSMTP, PreviewShare, and CleanLinks" "current managed product examples"
require_text "wp-product-orchestrator/SKILL.md" "Portfolio coverage drift" "orchestrator portfolio drift classification"
require_text "wp-product-orchestrator/SKILL.md" "portfolio control room plus one long-lived product-orchestrator thread per managed plugin" "thread topology"
require_text "wp-product-orchestrator/SKILL.md" "Product threads are user-visible control threads" "product thread protection"
require_text "wp-product-orchestrator/SKILL.md" "Portfolio execution drift" "portfolio execution drift classification"
require_text "wp-product-orchestrator/SKILL.md" "Product-idea issues require web research first" "product idea research gate"
require_text "wp-product-orchestrator/SKILL.md" 'Assign `@mehul0810`' "orchestrator issue assignee rule"
require_text "wp-product-orchestrator/SKILL.md" "competitor-neutral" "orchestrator public competitor neutrality"
require_text "wp-product-orchestrator/SKILL.md" 'no direct `main`' "worker no direct main rule"
require_text "wp-product-orchestrator/SKILL.md" "archive protected product/control threads" "protected thread archive gate"
require_text "wp-product-orchestrator/SKILL.md" "Use tool discovery before declaring worker/chat/worktree delegation unavailable" "orchestrator delegation tool discovery"
require_text "wp-product-orchestrator/SKILL.md" 'git rev-parse --show-toplevel' "orchestrator worktree repo-root verification"
require_text "wp-product-orchestrator/SKILL.md" "exact repo-root saved project" "orchestrator exact repo-root project guard"
require_text "wp-product-orchestrator/SKILL.md" "lands detached/wrong-base" "orchestrator unusable worktree guard"
require_text "wp-product-orchestrator/SKILL.md" "Missing milestone due dates are owner decisions, not blanket implementation blockers" "orchestrator due date not blanket blocker"
require_text "wp-product-orchestrator/SKILL.md" "Dirty or behind primary checkouts block direct edits, not fresh scoped worktree delegation" "orchestrator dirty checkout worktree delegation"
require_text "wp-product-orchestrator/SKILL.md" "name the exact hard blocker" "orchestrator exact deferred blocker"
require_text "wp-product-orchestrator/SKILL.md" "../shared/references/delegation-protocol.md" "orchestrator delegation protocol routing"
require_text "wp-product-orchestrator/SKILL.md" "../shared/references/github-communication-protocol.md" "orchestrator GitHub communication routing"
require_text "wp-product-orchestrator/SKILL.md" "../shared/references/commit-pr-discipline.md" "orchestrator commit/PR routing"
require_text "wp-product-orchestrator/SKILL.md" "../shared/references/weekly-wordpress-intelligence.md" "orchestrator weekly intelligence routing"
require_text "wp-product-orchestrator/SKILL.md" "../shared/references/self-improvement-loop.md" "orchestrator self-improvement routing"

require_text "shared/references/cto-orchestration-operating-model.md" "Source Of Truth Hierarchy" "source-of-truth hierarchy reference section"
require_text "shared/references/cto-orchestration-operating-model.md" "GitHub Issue-First Intake" "GitHub issue-first intake reference section"
require_text "shared/references/cto-orchestration-operating-model.md" "Portfolio Sweep Discipline" "portfolio sweep reference section"
require_text "shared/references/cto-orchestration-operating-model.md" "Quiet products must be included with" "quiet products inclusion"
require_text "shared/references/cto-orchestration-operating-model.md" "Open PRs/issues and CI/release blockers" "portfolio minimum status fields"
require_text "shared/references/cto-orchestration-operating-model.md" "Thread Topology" "thread topology reference section"
require_text "shared/references/cto-orchestration-operating-model.md" "Product Thread Ownership" "product thread ownership reference section"
require_text "shared/references/cto-orchestration-operating-model.md" "Portfolio Thread Ownership" "portfolio thread ownership reference section"
require_text "shared/references/cto-orchestration-operating-model.md" "WordPress.org Product Loop" "wordpress.org product loop"
require_text "shared/references/cto-orchestration-operating-model.md" "Competitor names may inform private research" "competitor-neutral public issues"
require_text "shared/references/cto-orchestration-operating-model.md" 'Assignee: `@mehul0810`' "issue assignee rule"
require_text "shared/references/delegation-protocol.md" "Delegated Thread Prompt" "delegated thread/worktree protocol"
require_text "shared/references/delegation-protocol.md" "no subdelegation unless the parent CTO thread asks" "delegated no-subdelegation rule"
require_text "shared/references/delegation-protocol.md" "Direct Execution Boundary" "direct CTO execution boundary"
require_text "shared/references/delegation-protocol.md" "delegate at least one bounded task" "mandatory delegation trigger"
require_text "shared/references/delegation-protocol.md" "Delegation decision: Delegated|Direct|Deferred" "delegation decision check-in line"
require_text "shared/references/delegation-protocol.md" "Prefer multi-agent/subagent delegation" "prefer internal subagent delegation"
require_text "shared/references/delegation-protocol.md" "Never archive user-created control or skill threads" "do not archive owner control threads"
require_text "shared/references/delegation-protocol.md" "Missing delegation after strategy" "delegation self-improvement classification"
require_text "shared/references/delegation-protocol.md" "Thread Boundary" "delegation thread boundary"
require_text "shared/references/delegation-protocol.md" 'Issue branch name and PR base; never direct `main`' "worker branch/base guard"
require_text "shared/references/delegation-protocol.md" "archive protected product/control threads" "worker protected archive guard"
require_text "shared/references/delegation-protocol.md" 'Look for `list_projects`, `create_thread`, `fork_thread`, `send_message_to_thread`' "delegation tool discovery requirement"
require_text "shared/references/delegation-protocol.md" "Worktree Creation Guard" "delegation worktree creation guard section"
require_text "shared/references/delegation-protocol.md" 'git rev-parse --show-toplevel' "delegation repo-root verification command"
require_text "shared/references/delegation-protocol.md" "missing exact repo project" "delegation missing repo project blocker"
require_text "shared/references/delegation-protocol.md" "unusable worktree" "delegation unusable worktree classification"
require_text "shared/references/delegation-protocol.md" "Dirty or behind primary checkouts block direct edits" "delegation dirty primary checkout rule"
require_text "shared/references/delegation-protocol.md" "OneSMTP #73" "delegation explicit branch-model blocker"
require_text "shared/references/release-train-discipline.md" "Do not create a next milestone prerelease" "release train production gate"
require_text "shared/references/release-train-discipline.md" "Milestones need due dates" "milestone due-date reference rule"
require_text "shared/references/release-train-discipline.md" '`main` is production release space only' "main production-only rule"
require_text "shared/references/release-train-discipline.md" "owner testing confirmation" "owner testing release readiness"
require_text "shared/references/release-train-discipline.md" "missing due date alone" "release missing due date not blocker"
require_text "shared/references/release-train-discipline.md" 'create or use `release/<milestone>`' "release branch creation/use rule"
require_text "shared/references/github-communication-protocol.md" "GitHub Issue And PR Comments" "GitHub issue and PR comments protocol"
require_text "shared/references/github-communication-protocol.md" "Codex:" "owner-authored Codex instruction handling"
require_text "shared/references/github-communication-protocol.md" "Write GitHub comments sparingly" "quiet GitHub write discipline"
require_text "shared/references/github-communication-protocol.md" "Do not post GitHub comments for routine notifications" "no routine GitHub notification comments"
require_text "shared/references/github-communication-protocol.md" "CTO control chat thread" "routine status routes to CTO chat"
require_text "shared/references/commit-pr-discipline.md" "type(scope): concise action" "commit convention"
require_text "shared/references/commit-pr-discipline.md" "Every PR must include" "PR template requirements"
require_text "shared/references/commit-pr-discipline.md" '`main` is production release space only' "commit-pr main production-only rule"
require_text "shared/references/commit-pr-discipline.md" "Worker PR Rule" "worker one issue one PR rule"
require_text "shared/references/commit-pr-discipline.md" "verified development base" "commit-pr verified development base"
require_text "shared/references/product-queue-triage.md" "Product-idea issues require web research" "product idea web research rule"
require_text "shared/references/product-queue-triage.md" 'Assign to `@mehul0810`' "product issue assignee rule"
require_text "shared/references/product-queue-triage.md" "Competitor names may inform private research" "product issue competitor-neutral rule"
require_text "shared/references/product-queue-triage.md" "not by themselves blockers" "queue due date blocker discipline"
require_text "shared/references/product-queue-triage.md" "fresh scoped worktree delegation" "queue dirty checkout worktree delegation"
require_text "shared/references/weekly-wordpress-intelligence.md" "Weekly WordPress Ecosystem Intelligence" "weekly WordPress ecosystem intelligence"
require_text "shared/references/self-improvement-loop.md" "Self-Improvement Loop" "self-improvement loop"
require_text "shared/references/self-improvement-loop.md" "Stale Learning Lifecycle" "self-improvement stale learning lifecycle"
require_text "shared/references/self-improvement-loop.md" "Durable Artifact Dedupe" "self-improvement durable artifact dedupe"
require_text "shared/references/self-improvement-loop.md" "Supersede note created" "self-improvement stale outcome labels"
require_text "shared/references/self-improvement-loop.md" "Open PRs and issues" "self-improvement duplicate artifact checks"
require_text "shared/references/self-improvement-loop.md" "Missing delegation after strategy" "self-improvement missing delegation label"
require_text "shared/references/self-improvement-loop.md" "Portfolio coverage drift" "self-improvement portfolio drift label"
require_text "shared/references/self-improvement-loop.md" "Portfolio execution drift" "self-improvement portfolio execution label"
require_text "shared/references/self-improvement-loop.md" "Product thread topology drift" "self-improvement topology drift label"
require_text "shared/references/self-improvement-loop.md" "Delegation unavailable without tool discovery" "self-improvement tool discovery label"
require_text "shared/references/self-improvement-loop.md" "Blanket blocker from due date, release branch, or dirty primary checkout" "self-improvement blanket blocker label"
require_text "shared/references/self-improvement-loop.md" "Stale Learning Lifecycle" "self-improvement stale-learning lifecycle section"
require_text "shared/references/self-improvement-loop.md" "Add" "self-improvement add lifecycle outcome"
require_text "shared/references/self-improvement-loop.md" "Correct" "self-improvement correct lifecycle outcome"
require_text "shared/references/self-improvement-loop.md" "Retire" "self-improvement retire lifecycle outcome"
require_text "shared/references/self-improvement-loop.md" "Supersede" "self-improvement supersede lifecycle outcome"
require_text "shared/references/self-improvement-loop.md" "Keep Watching" "self-improvement keep-watching lifecycle outcome"
require_text "shared/references/self-improvement-loop.md" "Ignore" "self-improvement ignore lifecycle outcome"
require_text "shared/references/self-improvement-loop.md" "Fixed now" "self-improvement fixed-now audit outcome"
require_text "shared/references/self-improvement-loop.md" "PR opened" "self-improvement PR-opened audit outcome"
require_text "shared/references/self-improvement-loop.md" "Supersede note created" "self-improvement supersede-note-created audit outcome"
require_text "shared/references/self-improvement-loop.md" "Detected only" "self-improvement detected-only audit outcome"
require_text "shared/references/self-improvement-loop.md" "Duplicate durable artifact" "self-improvement duplicate artifact label"
require_text "shared/references/self-improvement-loop.md" "Stale local-ref conclusion" "self-improvement stale local-ref label"
require_text "shared/references/self-improvement-loop.md" "Unclassified stale learning" "self-improvement unclassified stale learning label"
require_text "shared/references/self-improvement-loop.md" "Durable Artifact Dedupe" "self-improvement durable artifact dedupe section"
require_text "shared/references/self-improvement-loop.md" "Normalized rule slug" "self-improvement normalized slug dedupe"
require_text "shared/references/self-improvement-loop.md" "Open PRs and issues" "self-improvement open PR/issue dedupe"
require_text "shared/references/self-improvement-loop.md" "Recently merged PRs and closed issues" "self-improvement merged PR/closed issue dedupe"
require_text "shared/references/self-improvement-loop.md" "one compact rollup per date" "self-improvement same-day rollup dedupe"
require_text "shared/references/repo-product-docs-contract.md" "Product Truth Does Not Live Only In The Skill" "repo product docs contract"

if [ "$errors" -gt 0 ]; then
  echo "orchestration behavior audit failed: $errors missing guardrail(s)" >&2
  exit 1
fi

echo "orchestration behavior audit passed"
