#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
errors=0

require_text() {
  local file="$1"
  local text="$2"
  local label="$3"

  if grep -Fq "$text" "$repo_root/$file"; then
    echo "ok: $label"
  else
    echo "missing: $label ($file)" >&2
    errors=$((errors + 1))
  fi
}

reject_text() {
  local file="$1"
  local text="$2"
  local label="$3"

  if grep -Fq "$text" "$repo_root/$file"; then
    echo "unexpected: $label ($file)" >&2
    errors=$((errors + 1))
  else
    echo "ok: $label"
  fi
}

require_text "wp-expert/SKILL.md" "push only when explicitly asked or repo-local automation policy authorizes it" "wp-expert push authorization discipline"
require_text "wp-expert/SKILL.md" "../shared/references/live-proof-wordpress.md" "wp-expert live proof routing"
require_text "wp-expert/SKILL.md" "../shared/references/context-window-discipline.md" "wp-expert context window discipline routing"
require_text "wp-expert/SKILL.md" "references/architecture-decision-gate.md" "wp-expert architecture gate routing"
require_text "wp-expert/SKILL.md" "Stop after routing when the specialist is clear" "wp-expert no broad load after auto route"
require_text "wp-expert/SKILL.md" "wp-plugin-expert" "wp-expert plugin specialist routing"
require_text "wp-expert/SKILL.md" "wp-theme-expert" "wp-expert theme specialist routing"
require_text "wp-expert/SKILL.md" "wp-site-expert" "wp-expert site specialist routing"
require_text "wp-expert/SKILL.md" 'use `behavior-validator`' "wp-expert behavior validator routing"
require_text "wp-expert/SKILL.md" "wp-portfolio-cto" "wp-expert portfolio specialist routing"
require_text "wp-plugin-expert/SKILL.md" "references/router.md" "wp-plugin-expert modular router routing"
require_text "wp-plugin-expert/SKILL.md" "enterprise-code-quality-gate.md" "wp-plugin-expert quality contract routing"
require_text "wp-plugin-expert/SKILL.md" "worker-execution-discipline.md" "wp-plugin-expert worker execution routing"
require_text "wp-plugin-expert/SKILL.md" "design-intelligence-routing.md" "wp-plugin-expert design routing"
require_text "wp-plugin-expert/SKILL.md" "adjacent-finding-protocol.md" "wp-plugin-expert adjacent finding routing"
require_text "wp-plugin-expert/SKILL.md" "hand off instead of loading broad WordPress context" "wp-plugin-expert lane handoff"
require_text "wp-plugin-expert/references/router.md" "../../wp-expert/references/plugin-architecture.md" "wp-plugin-expert plugin architecture routing"
require_text "wp-theme-expert/SKILL.md" "references/router.md" "wp-theme-expert modular router routing"
require_text "wp-theme-expert/SKILL.md" "enterprise-code-quality-gate.md" "wp-theme-expert quality contract routing"
require_text "wp-theme-expert/SKILL.md" "worker-execution-discipline.md" "wp-theme-expert worker execution routing"
require_text "wp-theme-expert/SKILL.md" "design-intelligence-routing.md" "wp-theme-expert design routing"
require_text "wp-theme-expert/SKILL.md" "adjacent-finding-protocol.md" "wp-theme-expert adjacent finding routing"
require_text "wp-theme-expert/SKILL.md" "hand off instead of loading broad WordPress context" "wp-theme-expert lane handoff"
require_text "wp-theme-expert/references/router.md" "../../wp-expert/references/block-theme-architecture.md" "wp-theme-expert block theme routing"
require_text "wp-theme-expert/references/router.md" "../../wp-expert/references/standards-ci-github.md" "wp-theme-expert local-first CI routing"
require_text "wp-site-expert/SKILL.md" "references/router.md" "wp-site-expert modular router routing"
require_text "wp-site-expert/SKILL.md" "enterprise-code-quality-gate.md" "wp-site-expert quality contract routing"
require_text "wp-site-expert/SKILL.md" "worker-execution-discipline.md" "wp-site-expert worker execution routing"
require_text "wp-site-expert/SKILL.md" "design-intelligence-routing.md" "wp-site-expert design routing"
require_text "wp-site-expert/SKILL.md" "adjacent-finding-protocol.md" "wp-site-expert adjacent finding routing"
require_text "wp-site-expert/SKILL.md" "hand off instead of loading broad WordPress context" "wp-site-expert lane handoff"
require_text "wp-site-expert/references/router.md" "../../wp-expert/references/conversion-focused-website-engineering.md" "wp-site-expert conversion routing"
require_text "wp-site-expert/references/router.md" "../../wp-expert/references/standards-ci-github.md" "wp-site-expert local-first CI routing"
require_text "shared/references/project-subagent-routing.md" "Assign one lane and the narrowest skill/reference" "subagent specialist auto routing"
require_text "shared/references/project-subagent-routing.md" "Inspect the exact artifact first" "subagent exact artifact first"
require_text "shared/references/enterprise-code-quality-gate.md" "Every implementation should explicitly consider these quality dimensions" "shared quality contract dimensions"
require_text "shared/references/enterprise-code-quality-gate.md" '`Not applicable - reason`' "shared quality contract explicit exceptions"
require_text "shared/references/enterprise-code-quality-gate.md" "Local-First Validation Contract" "shared local-first validation contract"
require_text "shared/references/enterprise-code-quality-gate.md" "one canonical local validation command" "shared canonical local validation entrypoint"
require_text "shared/references/enterprise-code-quality-gate.md" "missing hosted CI as permission to skip tests" "shared no-CI no-skip rule"
require_text "wp-expert/references/standards-ci-github.md" "Local-First Automation Policy" "standards local-first automation policy"
require_text "wp-expert/references/standards-ci-github.md" 'Do not use `pull_request` or feature-branch `push` triggers' "standards no duplicate hosted triggers"
require_text "wp-expert/references/standards-ci-github.md" "Hosted PR/development CI is an exception" "standards hosted CI exception rule"
require_text "wp-expert/references/standards-ci-github.md" "same canonical full validation entrypoint used locally" "standards local release parity"
require_text "wp-expert/references/standards-ci-github.md" 'Use `workflow_dispatch` with explicit candidate SHA/version inputs' "standards safe release trigger"
require_text "wp-expert/references/standards-ci-github.md" 'never execute fork code through `pull_request_target`' "standards untrusted fork guard"
require_text "shared/references/release-train-discipline.md" "Hosted Automation Economy" "release hosted automation economy"
require_text "shared/references/release-train-discipline.md" "Reserve GitHub Actions for beta/prerelease/stable release transactions" "release-only hosted default"
require_text "shared/references/release-train-discipline.md" "saving Actions minutes never justifies skipping proof" "release proof preservation"
require_text "shared/references/repo-product-docs-contract.md" "canonical local fast/full/package commands" "repo docs local testing contract"
require_text "shared/references/repo-product-docs-contract.md" "release/prerelease GitHub Actions boundary" "repo docs hosted release boundary"
require_text "skill-evals/wp-expert-scenarios.md" "Local-first CI architecture" "local-first CI specialist scenario"
require_text "skill-evals/wp-expert-scenarios.md" "Hosted CI exception" "hosted CI exception scenario"
require_text "skill-evals/wp-product-orchestrator-scenarios.md" "Local-first Actions economy" "local-first CI PO scenario"
require_text "skill-evals/wp-portfolio-cto-scenarios.md" "Hosted CI spend drift" "hosted CI portfolio scenario"
require_text "EXAMPLES.md" "Local-First Validation And Release Actions" "local-first CI example"
reject_text "EXAMPLES.md" 'on: [push, pull_request]' "no stale blanket CI example"
require_text "shared/references/worker-execution-discipline.md" "Direct Task Decision Contract" "shared worker direct task contract"
require_text "shared/references/worker-execution-discipline.md" "Assumption And Confidence Gate" "shared worker assumption gate"
require_text "shared/references/worker-execution-discipline.md" "Worker Recovery Ladder" "shared worker recovery ladder"
require_text "shared/references/worker-execution-discipline.md" "Finish Pass" "shared worker finish pass"
require_text "shared/references/worker-execution-discipline.md" "Review Convergence Gate" "shared worker review convergence gate"
require_text "shared/references/worker-execution-discipline.md" "After two review-triggered edit cycles" "shared worker bounded review cycles"
require_text "AGENTS.md" "Skill Admission Gate" "repository skill admission gate"
require_text "AGENTS.md" "recurring portable workflow, tool boundary, or evidence contract" "repository skill admission criteria"
require_text "behavior-validator/SKILL.md" "Source-Blind Contract" "behavior validator source-blind contract"
require_text "behavior-validator/SKILL.md" "Do not inspect source files, diffs, tests, Git history" "behavior validator source exclusion"
require_text "behavior-validator/SKILL.md" "contaminated" "behavior validator contamination rule"
require_text "behavior-validator/SKILL.md" 'pass`, `fail`, `blocked`, or `out_of_scope`' "behavior validator clause states"
require_text "behavior-validator/references/wordpress-behavior-contract.md" "WordPress Anti-Cheat Probes" "WordPress anti-cheat probes"
require_text "behavior-validator/references/wordpress-behavior-contract.md" "install the release ZIP" "behavior validator packaged proof"
require_text "behavior-validator/references/wordpress-behavior-contract.md" "Settings/admin" "behavior validator settings persistence"
require_text "behavior-validator/references/wordpress-behavior-contract.md" "Block editor/FSE" "behavior validator editor persistence"
require_text "shared/references/live-proof-wordpress.md" "Independent Source-Blind Proof" "live proof source-blind route"
require_text "shared/references/live-proof-wordpress.md" 'source-blind `$behavior-validator` in `wp-proof`' "live proof packaged behavior route"
require_text "wp-plugin-expert/SKILL.md" '$behavior-validator' "plugin behavior validator route"
require_text "wp-theme-expert/SKILL.md" '$behavior-validator' "theme behavior validator route"
require_text "wp-site-expert/SKILL.md" '$behavior-validator' "site behavior validator route"
require_text "wp-product-orchestrator/SKILL.md" '$behavior-validator' "PO behavior validator route"
require_text "skill-evals/behavior-validator-scenarios.md" "Contaminated validator" "behavior validator contamination scenario"
require_text "skill-evals/behavior-validator-scenarios.md" "Static-only change" "behavior validator negative route scenario"
require_text "skill-evals/routing-collision-scenarios.md" "Implementation vs independent proof" "behavior validator split-ownership scenario"
require_text "shared/references/adjacent-finding-protocol.md" "Do not expand the current PR or task scope blindly" "shared adjacent finding scope boundary"
require_text "shared/references/adjacent-finding-protocol.md" "Adjacent findings" "shared adjacent finding worker output"
require_text "shared/references/design-intelligence-routing.md" 'Use `product-design:index` as the router only' "shared design router rule"
require_text "shared/references/design-intelligence-routing.md" "If UI changed, require screenshot proof" "shared design screenshot proof rule"
require_text "shared/references/design-intelligence-routing.md" "Convert Product Design findings into actionable acceptance criteria" "shared design actionable feedback rule"
require_text "shared/references/design-intelligence-routing.md" "product-experience-principles.md" "shared design product experience lens"
require_text "shared/references/design-intelligence-routing.md" "enterprise-design-judgment.md" "shared design enterprise judgment lens"
require_text "shared/references/product-experience-principles.md" "Build premium WordPress products that feel enterprise-grade, simple by default, and powerful when needed" "shared product experience goal"
require_text "shared/references/product-experience-principles.md" "The default path should be plug-and-play for non-technical users" "shared product experience plug-and-play principle"
require_text "shared/references/product-experience-principles.md" "Advanced configuration should exist for developers and power users" "shared product experience advanced-user principle"
require_text "shared/references/enterprise-design-judgment.md" "Enterprise design is not just polished UI" "shared enterprise design principle"
require_text "shared/references/enterprise-design-judgment.md" "claim, evidence, workflow, control, outcome" "shared enterprise proof-led hierarchy"
require_text "shared/references/enterprise-design-judgment.md" "governed workflows, approvals, auditability, policy, reliability" "shared enterprise AI workflow framing"
require_text "shared/references/project-subagent-routing.md" "adjacent findings" "subagent adjacent finding reporting"
require_text "shared/references/project-subagent-routing.md" "Convert Product Design feedback into acceptance criteria" "subagent design actionable feedback"
require_text "content-writer/SKILL.md" "verify shipped claims from current releases/tags" "content product truth gate"
require_text "content-writer/references/organic-search-content.md" '`shipped`, `verified limitation`, `planned/unreleased`, or `unknown`' "content claim classification"
require_text "skill-evals/content-writer-scenarios.md" "Unreleased feature" "content unshipped feature scenario"
require_text "content-writer/references/router.md" "human-writing-quality-gate.md" "content human writing route"
require_text "content-writer/references/human-writing-quality-gate.md" "Do not rewrite, score, or guess whether AI wrote the text" "content evidence-only detection"
require_text "content-writer/references/human-writing-quality-gate.md" "minimum effective edit" "content restrained editing"
require_text "content-writer/references/human-writing-quality-gate.md" "Do not maintain a universal banned-word or punctuation list" "content contextual style judgment"
require_text "skill-evals/content-writer-scenarios.md" "Evidence-based pattern detection" "content pattern detection scenario"
require_text "skill-evals/content-writer-scenarios.md" "Intentional rhetoric" "content intentional rhetoric scenario"
require_text "content-writer/SKILL.md" "references/router.md" "content focused router"
require_text "content-writer/references/router.md" "Enterprise product pages" "content enterprise writing route"
require_text "content-writer/references/enterprise-product-writing.md" "Two-Speed Reading" "content enterprise reader layers"
require_text "content-writer/references/enterprise-product-writing.md" "Never invent customer names, metrics, rankings, certifications, scale, savings, uptime" "content enterprise claim discipline"
require_text "content-writer/references/enterprise-product-writing.md" "Security/privacy" "content enterprise security tone"
require_text "content-writer/references/enterprise-product-writing.md" "where human approval is required" "content enterprise governed AI control"
require_text "skill-evals/content-writer-scenarios.md" "Enterprise page without customer metrics" "content enterprise missing metrics scenario"
require_text "skill-evals/content-writer-scenarios.md" "Unsupported category superlative" "content enterprise superlative scenario"
require_text "skill-evals/content-writer-scenarios.md" "Governed AI workflow" "content enterprise AI workflow scenario"
require_text "wp-expert/SKILL.md" 'use `loop-steward`' "wp-expert control-plane routing"
require_text "wp-portfolio-cto/SKILL.md" "Route backlog" "portfolio does not execute product backlog"
require_text "wp-product-orchestrator/SKILL.md" 'Cross-product governance belongs to `wp-portfolio-cto`' "product hands portfolio governance off"
require_text "shared/references/context-window-discipline.md" "Continuity-sensitive task" "context discipline continuity rule"
require_text "shared/references/context-window-discipline.md" "New or unrelated task" "context discipline fresh thread rule"
require_text "wp-expert/references/reference-routing-map.md" "## Risk-Triggered Overlays" "risk-triggered overlay routing"
require_text "wp-expert/references/architecture-decision-gate.md" "Source of truth" "architecture source-of-truth gate"
require_text "wp-expert/references/agent-behavior-eval-scenarios.md" "Block theme page from screenshot" "block theme editability eval scenario"
require_text "wp-expert/references/agent-behavior-eval-scenarios.md" "Milestone issue PR" "PR base eval scenario"
require_text "wp-expert/references/agent-behavior-eval-scenarios.md" "Plugin REST setting save" "REST settings eval scenario"
require_text "wp-expert/references/agent-behavior-eval-scenarios.md" "Unreleased feature rework" "unreleased compatibility eval scenario"
require_text "wp-expert/scripts/fse-design-map.sh" "Primary editing surface" "FSE editing surface field"
require_text "wp-expert/scripts/fse-design-map.sh" "Templates that must render Post Content" "FSE Post Content requirement field"
require_text "wp-expert/references/custom-block-theme-from-design.md" "Design-To-FSE Page Recipe" "design-to-FSE recipe"
require_text "wp-expert/references/custom-block-theme-from-design.md" "Image-To-WordPress Translation Loop" "image-to-wordpress translation loop"
require_text "wp-expert/references/custom-block-theme-from-design.md" "Surface Selection Matrix" "image-to-wordpress surface selection matrix"
require_text "wp-expert/references/standards-ci-github.md" "Push only when the user explicitly asks" "GitHub push authorization discipline"

if [ "$errors" -gt 0 ]; then
  echo "behavior audit failed: $errors missing guardrail(s)" >&2
  exit 1
fi

echo "behavior audit passed"
